Repository NeoJumper/MicroBankingSystem, pull requests merged in 2024-10, with the labels that each got.

#105 공통 예외처리
  src/main/java/com/kcc/banking/common/exception/CustomException.java
  src/main/java/com/kcc/banking/common/exception/ErrorCode.java
  src/main/java/com/kcc/banking/common/exception/GlobalExceptionHandler.java
  src/main/java/com/kcc/banking/common/exception/custom_exception/BadRequestException.java
  src/main/java/com/kcc/banking/common/exception/custom_exception/ForbiddenException.java
  src/main/java/com/kcc/banking/common/exception/custom_exception/NotFoundException.java
  src/main/java/com/kcc/banking/domain/employee/service/EmployeeService.java
Labels: ✨ Feature

#107 계좌이체 예외처리
  src/main/java/com/kcc/banking/common/exception/ErrorCode.java
  src/main/java/com/kcc/banking/domain/account/mapper/AccountMapper.java
  src/main/java/com/kcc/banking/domain/account/service/AccountService.java
  src/main/java/com/kcc/banking/domain/account_transfer/controller/TransferRestController.java
  src/main/java/com/kcc/banking/domain/account_transfer/service/TransferService.java
  src/main/resources/mapper/accountMapper.xml
  src/main/webapp/resources/js/page/account-transfer.js
Labels: ✨ Feature

#108 예외처리 FIX
  src/main/java/com/kcc/banking/common/exception/ErrorCode.java
  src/main/java/com/kcc/banking/domain/account/service/AccountService.java
  src/main/java/com/kcc/banking/domain/account_transfer/service/TransferService.java
Labels: 🐛 BugFix

#109 Feature/#103 account close detail modal UI
  src/main/java/com/kcc/banking/domain/account_close/dto/request/AccountStatus.java
  src/main/java/com/kcc/banking/domain/account_close/dto/request/CloseTrade.java
  src/main/java/com/kcc/banking/domain/account_close/service/AccountCloseService.java
  src/main/resources/mapper/accountCloseMapper.xml
  src/main/webapp/WEB-INF/views/account_close/account-close-cancel.jsp
  src/main/webapp/WEB-INF/views/account_close/account-close.jsp
  src/main/webapp/resources/css/page/account-close.css
  src/main/webapp/resources/js/page/account-close-cancel.js
  src/main/webapp/resources/js/page/account-close.js
Labels: ✨ Feature

#110 비밀번호 인증 및 예외처리
  src/main/java/com/kcc/banking/common/auth/SecurityConfig.java
  src/main/java/com/kcc/banking/domain/account_transfer/mapper/TransferMapper.java
  src/main/java/com/kcc/banking/domain/account_transfer/service/TransferService.java
  src/main/webapp/WEB-INF/views/transfer/account-transfer.jsp
  src/main/webapp/resources/css/styles.css
  src/main/webapp/resources/js/page/account-transfer.js
Labels: ✨ Feature

#112 영업일 변경 기능 구현
  src/main/java/com/kcc/banking/domain/business_day/controller/BusinessDayRestController.java
  src/main/java/com/kcc/banking/domain/business_day/dto/request/BusinessDayChange.java
  src/main/java/com/kcc/banking/domain/business_day/dto/request/BusinessDayUpdate.java
  src/main/java/com/kcc/banking/domain/business_day/dto/request/WorkerData.java
  src/main/java/com/kcc/banking/domain/business_day/event/BusinessDayChangeEvent.java
  src/main/java/com/kcc/banking/domain/business_day/listener/BusinessDayEventListener.java
  src/main/java/com/kcc/banking/domain/business_day/mapper/BusinessDayMapper.java
  src/main/java/com/kcc/banking/domain/business_day/service/BusinessDayService.java
  src/main/java/com/kcc/banking/domain/business_day_close/controller/BusinessDayCloseController.java
  src/main/java/com/kcc/banking/domain/business_day_close/controller/BusinessDayCloseRestController.java
  src/main/java/com/kcc/banking/domain/business_day_close/dto/request/BranchClosingCreate.java
  src/main/java/com/kcc/banking/domain/business_day_close/dto/request/EmployeeClosingCreate.java
  src/main/java/com/kcc/banking/domain/business_day_close/dto/response/ClosingData.java
  src/main/java/com/kcc/banking/domain/business_day_close/mapper/BusinessDayCloseMapper.java
  src/main/java/com/kcc/banking/domain/business_day_close/service/BusinessDayCloseService.java
  src/main/java/com/kcc/banking/domain/employee/controller/EmployeeRestController.java
  src/main/java/com/kcc/banking/domain/employee/mapper/EmployeeMapper.java
  src/main/java/com/kcc/banking/domain/employee/service/EmployeeService.java
  src/main/resources/mapper/businessDayCloseMapper.xml
  src/main/resources/mapper/businessDayMapper.xml
  src/main/resources/mapper/employeeMapper.xml
  src/main/webapp/resources/components/modal/business-day-update-modal.jsp
  src/main/webapp/resources/js/modal/business-day-update-modal.js
Labels: ✨ Feature

#114 이자 생성 기능구현
  src/main/java/com/kcc/banking/domain/account/dto/response/AccountDetailForInterest.java
  src/main/java/com/kcc/banking/domain/account/mapper/AccountMapper.java
  src/main/java/com/kcc/banking/domain/account/service/AccountService.java
  src/main/java/com/kcc/banking/domain/business_day/listener/BusinessDayEventListener.java
  src/main/java/com/kcc/banking/domain/business_day_close/service/BusinessDayCloseService.java
  src/main/java/com/kcc/banking/domain/interest/dto/request/InterestCreate.java
  src/main/java/com/kcc/banking/domain/interest/mapper/InterestMapper.java
  src/main/java/com/kcc/banking/domain/interest/service/InterestService.java
  src/main/resources/mapper/accountMapper.xml
  src/main/resources/mapper/interestMapper.xml
  src/main/resources/schema.sql
Labels: ✨ Feature

#115 거래내역 총 입금액 출금액 기능 구현
  src/main/java/com/kcc/banking/domain/account/controller/AccountController.java
  src/main/java/com/kcc/banking/domain/trade/controller/TradeController.java
  src/main/java/com/kcc/banking/domain/trade/controller/TradeRestController.java
  src/main/java/com/kcc/banking/domain/trade/dto/response/TradeCashOfPerAccount.java
  src/main/java/com/kcc/banking/domain/trade/dto/response/TradeOfList.java
  src/main/java/com/kcc/banking/domain/trade/service/TradeService.java
  src/main/resources/data.sql
  src/main/webapp/WEB-INF/views/trade/trade-list.jsp
  src/main/webapp/resources/js/page/trade-list.js
Labels: ✨ Feature

#118 Service에서의 비밀번호 검증 추가 & 페이지 redirection
  src/main/java/com/kcc/banking/common/exception/ErrorCode.java
  src/main/java/com/kcc/banking/domain/account/service/AccountService.java
  src/main/java/com/kcc/banking/domain/account_transfer/controller/TransferRestController.java
  src/main/java/com/kcc/banking/domain/account_transfer/dto/request/TransferCreate.java
  src/main/java/com/kcc/banking/domain/account_transfer/service/TransferService.java
  src/main/webapp/resources/components/modal/transfer-result-modal.jsp
  src/main/webapp/resources/js/modal/transfer-result-modal.js
  src/main/webapp/resources/js/page/account-transfer.js
Labels: ✨ Feature

#119 Feature/#103 account close, account close cancel detail modal UI
  src/main/java/com/kcc/banking/domain/account_close/dto/request/CloseTrade.java
  src/main/java/com/kcc/banking/domain/account_close/service/AccountCloseService.java
  src/main/webapp/WEB-INF/views/account_close/account-close-cancel.jsp
  src/main/webapp/WEB-INF/views/account_close/account-close.jsp
  src/main/webapp/resources/components/modal/account-close-cancel-result-modal.jsp
  src/main/webapp/resources/components/modal/account-close-result-modal.jsp
  src/main/webapp/resources/js/page/account-close-cancel.js
  src/main/webapp/resources/js/page/account-close.js
Labels: ✨ Feature

#120 영업일 관리 예외처리
  src/main/java/com/kcc/banking/common/exception/ErrorCode.java
  src/main/java/com/kcc/banking/domain/business_day/controller/BusinessDayRestController.java
  src/main/java/com/kcc/banking/domain/business_day/dto/response/BusinessDay.java
  src/main/java/com/kcc/banking/domain/business_day/listener/BusinessDayEventListener.java
  src/main/java/com/kcc/banking/domain/business_day/mapper/BusinessDayMapper.java
  src/main/java/com/kcc/banking/domain/business_day/service/BusinessDayService.java
  src/main/java/com/kcc/banking/domain/business_day_close/mapper/BusinessDayCloseMapper.java
  src/main/java/com/kcc/banking/domain/business_day_close/service/BusinessDayCloseService.java
  src/main/java/com/kcc/banking/domain/common/mapper/CommonMapper.java
  src/main/java/com/kcc/banking/domain/common/service/CommonService.java
  src/main/java/com/kcc/banking/domain/interest/dto/request/InterestCreate.java
  src/main/java/com/kcc/banking/domain/interest/service/InterestService.java
  src/main/resources/mapper/businessDayCloseMapper.xml
  src/main/resources/mapper/businessDayMapper.xml
  src/main/resources/mapper/commenMapper.xml
  src/main/webapp/WEB-INF/views/business-day/business-day-management.jsp
  src/main/webapp/WEB-INF/views/business-day/employee-close.jsp
  src/main/webapp/WEB-INF/views/business-day/manager-close.jsp
  src/main/webapp/resources/js/header.js
  src/main/webapp/resources/js/modal/business-day-update-modal.js
  src/main/webapp/resources/js/page/business-day-management.js
  src/main/webapp/resources/js/page/employee-close.js
  src/main/webapp/resources/js/page/manager-close.js
Labels: ✨ Feature

#122 Feature/#103 account close detail modal UI
  src/main/java/com/kcc/banking/domain/account_close/service/AccountCloseService.java
Labels: ✨ Feature

#124 공통 컬럼 추가 기능 구현
  src/main/java/com/kcc/banking/domain/business_day_close/dto/request/BranchClosingCreate.java
  src/main/java/com/kcc/banking/domain/business_day_close/dto/request/EmployeeClosingCreate.java
  src/main/java/com/kcc/banking/domain/business_day_close/service/BusinessDayCloseService.java
  src/main/java/com/kcc/banking/domain/common/service/CommonService.java
  src/main/java/com/kcc/banking/domain/employee/dto/request/EmployeeCreate.java
  src/main/java/com/kcc/banking/domain/employee/dto/request/EmployeeUpdate.java
  src/main/java/com/kcc/banking/domain/employee/service/EmployeeService.java
  src/main/java/com/kcc/banking/domain/interest/dto/request/InterestCreate.java
  src/main/java/com/kcc/banking/domain/interest/service/InterestService.java
  src/main/resources/mapper/businessDayCloseMapper.xml
  src/main/resources/mapper/employeeMapper.xml
  src/main/resources/mapper/interestMapper.xml
  src/main/webapp/WEB-INF/views/employee/employee-save.jsp
  src/main/webapp/resources/js/page/business-day-management.js
  src/main/webapp/resources/js/page/employee-save.js
Labels: 🐛 BugFix, ✨ Feature, ♻️ Refactor

#127 헤더 연결
  src/main/java/com/kcc/banking/domain/account_close/controller/AccountCloseController.java
  src/main/java/com/kcc/banking/domain/employee/controller/EmployeeController.java
  src/main/webapp/resources/components/header.jsp
  src/main/webapp/resources/components/sidebar.jsp
  src/main/webapp/resources/css/header.css
  src/main/webapp/resources/js/header.js
  src/main/webapp/resources/js/modal/employee-detail-modal.js
  src/main/webapp/resources/js/page/employee-save.js
  src/main/webapp/resources/js/sidebar.js
Labels: ✨ Feature

#129 현금 입출금거래 UI 구현 / 기능 구현
  src/main/java/com/kcc/banking/HelloController.java
  src/main/java/com/kcc/banking/common/exception/ErrorCode.java
  src/main/java/com/kcc/banking/domain/account_transfer/controller/TransferController.java
  src/main/java/com/kcc/banking/domain/account_transfer/controller/TransferRestController.java
  src/main/java/com/kcc/banking/domain/account_transfer/mapper/TransferMapper.java
  src/main/java/com/kcc/banking/domain/account_transfer/service/TransferService.java
  src/main/java/com/kcc/banking/domain/trade/controller/TradeController.java
  src/main/java/com/kcc/banking/domain/trade/controller/TradeRestController.java
  src/main/java/com/kcc/banking/domain/trade/dto/request/TradeCreate.java
  src/main/java/com/kcc/banking/domain/trade/dto/response/TradeDetail.java
  src/main/java/com/kcc/banking/domain/trade/mapper/TradeMapper.java
  src/main/java/com/kcc/banking/domain/trade/service/TradeService.java
  src/main/resources/mapper/tradeMapper.xml
  src/main/resources/mapper/transferMapper.xml
  src/main/webapp/WEB-INF/views/error1.jsp
  src/main/webapp/WEB-INF/views/index.jsp
  src/main/webapp/WEB-INF/views/trade/trade-cash.jsp
  src/main/webapp/WEB-INF/views/transfer/account-transfer-cancel.jsp
  src/main/webapp/WEB-INF/views/transfer/account-transfer.jsp
  src/main/webapp/resources/components/modal/trade-cash-result-modal.jsp
  src/main/webapp/resources/components/modal/transfer-result-modal.jsp
  src/main/webapp/resources/css/page/trade-cash.css
  src/main/webapp/resources/js/modal/account-search-modal.js
  src/main/webapp/resources/js/page/account-transfer-cancel.js
  src/main/webapp/resources/js/page/account-transfer.js
  src/main/webapp/resources/js/page/trade-cash.js
Labels: ✨ Feature

#131 로그아웃 기능 구현
  src/main/java/com/kcc/banking/common/auth/SecurityConfig.java
  src/main/webapp/resources/js/sidebar.js
Labels: ✨ Feature, ♻️ Refactor

#133 URL연결 버그수정
  src/main/webapp/resources/js/sidebar.js
Labels: 🐛 BugFix

#134 거래 취소 요청 구현
  src/main/java/com/kcc/banking/domain/account_transfer/controller/TransferRestController.java
  src/main/java/com/kcc/banking/domain/account_transfer/dto/request/TradeCancelRequest.java
  src/main/java/com/kcc/banking/domain/account_transfer/mapper/TransferMapper.java
  src/main/java/com/kcc/banking/domain/account_transfer/service/TransferService.java
  src/main/resources/mapper/transferMapper.xml
  src/main/webapp/WEB-INF/views/transfer/account-transfer-cancel.jsp
  src/main/webapp/resources/js/page/account-transfer-cancel.js
Labels: ✨ Feature

#136 서브 페이지 URL 매핑 오류 수정
  src/main/java/com/kcc/banking/domain/account_transfer/controller/TransferController.java
  src/main/webapp/WEB-INF/views/employee/employee-save.jsp
  src/main/webapp/resources/js/header.js
  src/main/webapp/resources/js/sidebar.js
Labels: 🐛 BugFix, ♻️ Refactor

#137 거래내역 페이징 기능 구현
  src/main/java/com/kcc/banking/domain/trade/controller/TradeRestController.java
  src/main/java/com/kcc/banking/domain/trade/dto/request/TradeSearch.java
  src/main/java/com/kcc/banking/domain/trade/dto/response/Criteria.java
  src/main/java/com/kcc/banking/domain/trade/dto/response/PageDTO.java
  src/main/java/com/kcc/banking/domain/trade/dto/response/PagingInfoOfTradeList.java
  src/main/java/com/kcc/banking/domain/trade/dto/response/TradeCashOfPerAccount.java
  src/main/java/com/kcc/banking/domain/trade/dto/response/TradeInfoOfPerAccount.java
  src/main/java/com/kcc/banking/domain/trade/mapper/TradeMapper.java
  src/main/java/com/kcc/banking/domain/trade/service/TradeService.java
  src/main/resources/data.sql
  src/main/resources/mapper/tradeMapper.xml
  src/main/webapp/WEB-INF/views/trade/trade-list.jsp
  src/main/webapp/resources/css/page/trade-list.css
  src/main/webapp/resources/css/styles.css
  src/main/webapp/resources/js/modal/search-customer-modal.js
  src/main/webapp/resources/js/page/account-open.js
  src/main/webapp/resources/js/page/trade-list.js
Labels: ✨ Feature

#141 행원 수정 Bugfix
  src/main/resources/mapper/interestMapper.xml
  src/main/webapp/WEB-INF/views/employee/employee-update.jsp
  src/main/webapp/resources/js/page/employee-update.js
Labels: 🐛 BugFix

#143 Feature/#123 account close table add
  src/main/java/com/kcc/banking/domain/account/dto/request/SearchAccountOfModal.java
  src/main/java/com/kcc/banking/domain/account/dto/response/AccountOfModal.java
  src/main/java/com/kcc/banking/domain/account_close/controller/AccountCloseController.java
  src/main/java/com/kcc/banking/domain/trade/service/TradeService.java
  src/main/resources/mapper/accountMapper.xml
  src/main/webapp/WEB-INF/views/account_close/account-close-cancel.jsp
  src/main/webapp/WEB-INF/views/account_close/account-close.jsp
  src/main/webapp/resources/js/modal/account-search-modal.js
  src/main/webapp/resources/js/page/account-close-cancel.js
  src/main/webapp/resources/js/page/account-close.js
Labels: ✨ Feature

#145 더미데이터 수정
  src/main/java/com/kcc/banking/domain/account_transfer/controller/TransferRestController.java
  src/main/resources/data.sql
  src/main/resources/schema.sql
  src/main/webapp/WEB-INF/views/transfer/account-transfer-cancel.jsp
  src/main/webapp/resources/css/page/account-transfer-cancel.css
  src/main/webapp/resources/js/modal/account-search-modal.js
  src/main/webapp/resources/js/page/account-transfer-cancel.js
Labels: ♻️ Refactor

#147 권한에 따른 헤더 사이드바 분리
  src/main/java/com/kcc/banking/common/auth/SecurityConfig.java
  src/main/java/com/kcc/banking/domain/business_day/controller/BusinessDayRestController.java
  src/main/java/com/kcc/banking/domain/employee/controller/EmployeeController.java
  src/main/java/com/kcc/banking/domain/employee/controller/EmployeeRestController.java
  src/main/webapp/WEB-INF/views/auth/join-form.jsp
  src/main/webapp/WEB-INF/views/auth/login-form.jsp
  src/main/webapp/resources/components/header.jsp
  src/main/webapp/resources/js/header.js
  src/main/webapp/resources/js/join-form.js
  src/main/webapp/resources/js/modal/business-day-update-modal.js
  src/main/webapp/resources/js/page/business-day-management.js
  src/main/webapp/resources/js/page/employee-close.js
  src/main/webapp/resources/js/page/employee-save.js
  src/main/webapp/resources/js/page/employee-update.js
  src/main/webapp/resources/js/page/manager-close.js
  src/main/webapp/resources/js/page/trade-cash.js
  src/main/webapp/resources/js/sidebar.js
Labels: ✨ Feature, ♻️ Refactor

#149 거래 확인 내역, 거래 취소 내역에 고객 이름 추가
  src/main/java/com/kcc/banking/domain/account/dto/response/AccountDetail.java
  src/main/java/com/kcc/banking/domain/account_transfer/dto/response/TransferDetail.java
  src/main/java/com/kcc/banking/domain/account_transfer/service/TransferService.java
  src/main/resources/mapper/accountMapper.xml
  src/main/resources/mapper/transferMapper.xml
  src/main/webapp/WEB-INF/views/transfer/account-transfer-cancel.jsp
  src/main/webapp/resources/components/modal/transfer-result-modal.jsp
  src/main/webapp/resources/js/page/account-transfer-cancel.js
  src/main/webapp/resources/js/page/account-transfer.js
Labels: ✨ Feature

#150 권한 처리
  src/main/java/com/kcc/banking/HelloController.java
  src/main/java/com/kcc/banking/common/auth/SecurityConfig.java
  src/main/java/com/kcc/banking/domain/employee/controller/EmployeeRestController.java
  src/main/resources/data.sql
  src/main/resources/schema.sql
  src/main/webapp/WEB-INF/views/error-403.jsp
  src/main/webapp/WEB-INF/views/error-404.jsp
  src/main/webapp/resources/js/header.js
  src/main/webapp/resources/js/sidebar.js
Labels: ✨ Feature, ♻️ Refactor

#153 더미 데이터 추가
  src/main/resources/data.sql
Labels: 🛠 Setting

#160 Feature/#123 account close table add
  src/main/resources/data.sql
Labels: ✨ Feature

#162 계좌 개설 및 해지 기능 통합
  src/main/java/com/kcc/banking/common/exception/ErrorCode.java
  src/main/java/com/kcc/banking/domain/account/controller/AccountController.java
  src/main/java/com/kcc/banking/domain/account/controller/AccountRestController.java
  src/main/java/com/kcc/banking/domain/account/dto/request/AccountStatus.java
  src/main/java/com/kcc/banking/domain/account/dto/request/StatusWithTrade.java
  src/main/java/com/kcc/banking/domain/account/dto/response/CloseAccountTotal.java
  src/main/java/com/kcc/banking/domain/account/mapper/AccountMapper.java
  src/main/java/com/kcc/banking/domain/account/service/AccountService.java
  src/main/java/com/kcc/banking/domain/account_close/controller/AccountCloseController.java
  src/main/java/com/kcc/banking/domain/account_close/controller/AccountCloseRestController.java
  src/main/java/com/kcc/banking/domain/account_close/mapper/AccountCloseMapper.java
  src/main/java/com/kcc/banking/domain/business_day/dto/request/BusinessDayUpdate.java
  src/main/java/com/kcc/banking/domain/common/dto/request/CurrentData.java
  src/main/java/com/kcc/banking/domain/common/dto/request/RegistrantNameAndInfoAndDate.java
  src/main/java/com/kcc/banking/domain/common/service/CommonService.java
  src/main/java/com/kcc/banking/domain/interest/dto/request/AccountIdWithExpireDate.java
  src/main/java/com/kcc/banking/domain/interest/dto/request/PaymentStatus.java
  src/main/java/com/kcc/banking/domain/interest/dto/request/RollbackPaymentStatus.java
  src/main/java/com/kcc/banking/domain/interest/dto/response/InterestSum.java
  src/main/java/com/kcc/banking/domain/interest/mapper/InterestMapper.java
  src/main/java/com/kcc/banking/domain/interest/service/InterestService.java
  src/main/java/com/kcc/banking/domain/trade/dto/request/CloseAccount.java
  src/main/java/com/kcc/banking/domain/trade/dto/request/CloseTrade.java
  src/main/java/com/kcc/banking/domain/trade/mapper/TradeMapper.java
  src/main/java/com/kcc/banking/domain/trade/service/AccountTradeFacade.java
  src/main/java/com/kcc/banking/domain/trade/service/TradeService.java
  src/main/resources/mapper/accountCloseMapper.xml
  src/main/resources/mapper/accountMapper.xml
  src/main/resources/mapper/interestMapper.xml
  src/main/resources/mapper/tradeMapper.xml
  src/main/webapp/resources/js/modal/account-search-modal.js
  src/main/webapp/resources/js/page/account-close-cancel.js
  src/main/webapp/resources/js/page/account-close.js
  src/main/webapp/resources/js/page/account-open.js
  src/main/webapp/resources/js/page/account-transfer.js
  src/main/webapp/resources/js/page/trade-cash.js
Labels: ♻️ Refactor

#164 거래, 계좌이체 도메인 통합
  src/main/java/com/kcc/banking/domain/account/controller/AccountController.java
  src/main/java/com/kcc/banking/domain/account/mapper/AccountMapper.java
  src/main/java/com/kcc/banking/domain/account/service/AccountService.java
  src/main/java/com/kcc/banking/domain/account_transfer/controller/TransferController.java
  src/main/java/com/kcc/banking/domain/account_transfer/controller/TransferRestController.java
  src/main/java/com/kcc/banking/domain/account_transfer/mapper/TransferMapper.java
  src/main/java/com/kcc/banking/domain/account_transfer/service/TransferService.java
  src/main/java/com/kcc/banking/domain/trade/controller/TradeController.java
  src/main/java/com/kcc/banking/domain/trade/controller/TradeRestController.java
  src/main/java/com/kcc/banking/domain/trade/dto/request/TradeCancelRequest.java
  src/main/java/com/kcc/banking/domain/trade/dto/request/TransferCreate.java
  src/main/java/com/kcc/banking/domain/trade/dto/response/TransferDetail.java
  src/main/java/com/kcc/banking/domain/trade/mapper/TradeMapper.java
  src/main/java/com/kcc/banking/domain/trade/service/AccountTradeFacade.java
  src/main/java/com/kcc/banking/domain/trade/service/TradeService.java
  src/main/resources/mapper/accountMapper.xml
  src/main/resources/mapper/tradeMapper.xml
  src/main/resources/mapper/transferMapper.xml
  src/main/webapp/WEB-INF/views/account/account-close-cancel.jsp
  src/main/webapp/WEB-INF/views/account/account-close.jsp
  src/main/webapp/WEB-INF/views/trade/account-transfer-cancel.jsp
  src/main/webapp/WEB-INF/views/trade/account-transfer.jsp
  src/main/webapp/WEB-INF/views/trade/cash-trade.jsp
  src/main/webapp/resources/js/sidebar.js
Labels: ♻️ Refactor

#166 계좌 거래 Facade 패턴 적용
  src/main/java/com/kcc/banking/domain/account/controller/AccountRestController.java
  src/main/java/com/kcc/banking/domain/account/dto/request/AccountUpdate.java
  src/main/java/com/kcc/banking/domain/account/dto/request/StatusWithTrade.java
  src/main/java/com/kcc/banking/domain/account/mapper/AccountMapper.java
  src/main/java/com/kcc/banking/domain/account/service/AccountService.java
  src/main/java/com/kcc/banking/domain/interest/dto/request/PaymentStatus.java
  src/main/java/com/kcc/banking/domain/interest/service/InterestService.java
  src/main/java/com/kcc/banking/domain/trade/controller/TradeRestController.java
  src/main/java/com/kcc/banking/domain/trade/dto/request/CashTradeCreate.java
  src/main/java/com/kcc/banking/domain/trade/dto/request/TradeCreate.java
  src/main/java/com/kcc/banking/domain/trade/dto/request/TransferTradeCreate.java
  src/main/java/com/kcc/banking/domain/trade/dto/response/TradeDetail.java
  src/main/java/com/kcc/banking/domain/trade/mapper/TradeMapper.java
  src/main/java/com/kcc/banking/domain/trade/service/AccountTradeFacade.java
  src/main/java/com/kcc/banking/domain/trade/service/TradeService.java
  src/main/resources/mapper/accountMapper.xml
  src/main/resources/mapper/tradeMapper.xml
  src/main/webapp/resources/js/page/account-close.js
  src/main/webapp/resources/js/page/trade-cash.js
Labels: ♻️ Refactor

#169 account pw 검증 메서드 변경 JS
  src/main/webapp/resources/js/page/account-close-cancel.js
  src/main/webapp/resources/js/page/account-close.js
Labels: ♻️ Refactor

#170 Bugfix/#168
  src/main/java/com/kcc/banking/domain/account/dto/request/AccountUpdate.java
  src/main/java/com/kcc/banking/domain/account/mapper/AccountMapper.java
  src/main/java/com/kcc/banking/domain/account/service/AccountService.java
  src/main/java/com/kcc/banking/domain/interest/dto/request/AccountIdWithExpireDate.java
  src/main/java/com/kcc/banking/domain/interest/dto/request/RollbackPaymentStatus.java
  src/main/java/com/kcc/banking/domain/trade/service/AccountTradeFacade.java
  src/main/resources/mapper/accountMapper.xml
Labels: 🐛 BugFix

#172 해지 취소 버그 수정
  src/main/java/com/kcc/banking/domain/interest/service/InterestService.java
  src/main/java/com/kcc/banking/domain/trade/controller/TradeRestController.java
  src/main/java/com/kcc/banking/domain/trade/dto/response/CloseCancelDetail.java
  src/main/java/com/kcc/banking/domain/trade/service/AccountTradeFacade.java
  src/main/java/com/kcc/banking/domain/trade/service/TradeService.java
  src/main/resources/mapper/interestMapper.xml
  src/main/resources/mapper/tradeMapper.xml
  src/main/webapp/resources/components/modal/account-close-cancel-result-modal.jsp
  src/main/webapp/resources/js/page/account-close-cancel.js
Labels: 🐛 BugFix

#173 account close, account close cancel 해지 및 취소 버튼 클릭 후 비활성화
  src/main/webapp/resources/js/page/account-close-cancel.js
  src/main/webapp/resources/js/page/account-close.js
Labels: ♻️ Refactor

#176 해지 취소 리팩토링
  src/main/java/com/kcc/banking/domain/account/controller/AccountRestController.java
  src/main/java/com/kcc/banking/domain/interest/dto/request/PaymentStatusRollback.java
  src/main/java/com/kcc/banking/domain/interest/dto/request/PaymentStatusUpdate.java
  src/main/java/com/kcc/banking/domain/interest/mapper/InterestMapper.java
  src/main/java/com/kcc/banking/domain/interest/service/InterestService.java
  src/main/java/com/kcc/banking/domain/trade/controller/TradeRestController.java
  src/main/java/com/kcc/banking/domain/trade/mapper/TradeMapper.java
  src/main/java/com/kcc/banking/domain/trade/service/AccountTradeFacade.java
  src/main/java/com/kcc/banking/domain/trade/service/TradeService.java
  src/main/resources/mapper/interestMapper.xml
  src/main/resources/mapper/tradeMapper.xml
  src/main/webapp/resources/js/page/account-transfer-cancel.js
Labels: ♻️ Refactor

#178 계좌 잔액 및 상태변경 공통 처리
  src/main/java/com/kcc/banking/domain/account/service/AccountService.java
  src/main/java/com/kcc/banking/domain/trade/service/AccountTradeFacade.java
  src/main/resources/mapper/accountMapper.xml
Labels: ♻️ Refactor

#180 공통 CSS 수정
  src/main/webapp/resources/assets/neobank-logo.png
  src/main/webapp/resources/components/header.jsp
  src/main/webapp/resources/components/sidebar.jsp
  src/main/webapp/resources/css/header.css
  src/main/webapp/resources/css/sidebar.css
  src/main/webapp/resources/css/styles.css
  src/main/webapp/resources/js/sidebar.js
Labels: ♻️ Refactor

#182 Refactor/#180 account
  src/main/java/com/kcc/banking/domain/account/controller/AccountRestController.java
  src/main/java/com/kcc/banking/domain/account/dto/request/AccountCreate.java
  src/main/java/com/kcc/banking/domain/account/dto/request/AccountOpen.java
  src/main/java/com/kcc/banking/domain/account/service/AccountService.java
  src/main/java/com/kcc/banking/domain/trade/controller/TradeRestController.java
  src/main/java/com/kcc/banking/domain/trade/service/AccountTradeFacade.java
  src/main/java/com/kcc/banking/domain/trade/service/TradeService.java
  src/main/resources/mapper/accountMapper.xml
Labels: ♻️ Refactor

#185 거래 취소 요청 상태 변경 & 역거래 생성 추가
  src/main/java/com/kcc/banking/common/exception/ErrorCode.java
  src/main/java/com/kcc/banking/domain/trade/controller/TradeRestController.java
  src/main/java/com/kcc/banking/domain/trade/dto/request/TradeCancelRequest.java
  src/main/java/com/kcc/banking/domain/trade/dto/request/TransferTradeCreate.java
  src/main/java/com/kcc/banking/domain/trade/service/AccountTradeFacade.java
  src/main/java/com/kcc/banking/domain/trade/service/TradeService.java
  src/main/webapp/resources/js/page/account-transfer.js
Labels: ✨ Feature

#187 영업일 마감 기능 마무리
  src/main/java/com/kcc/banking/domain/business_day/service/BusinessDayManagementFacade.java
  src/main/java/com/kcc/banking/domain/business_day_close/controller/BusinessDayCloseController.java
  src/main/java/com/kcc/banking/domain/business_day_close/controller/BusinessDayCloseRestController.java
  src/main/java/com/kcc/banking/domain/business_day_close/dto/request/VaultCashRequest.java
  src/main/java/com/kcc/banking/domain/business_day_close/dto/response/ManagerClosingData.java
  src/main/java/com/kcc/banking/domain/business_day_close/mapper/BusinessDayCloseMapper.java
  src/main/java/com/kcc/banking/domain/business_day_close/service/BusinessDayCloseService.java
  src/main/resources/data.sql
  src/main/resources/mapper/businessDayCloseMapper.xml
  src/main/webapp/WEB-INF/views/business-day/employee-close.jsp
  src/main/webapp/WEB-INF/views/business-day/manager-close.jsp
  src/main/webapp/resources/js/page/employee-close.js
  src/main/webapp/resources/js/page/manager-close.js
Labels: ✨ Feature

#191 현금 거래 시 개인 마감 테이블 입출금액 변경
  src/main/java/com/kcc/banking/domain/account/dto/request/AccountOpen.java
  src/main/java/com/kcc/banking/domain/business_day_close/dto/request/EmployeeClosingUpdate.java
  src/main/java/com/kcc/banking/domain/business_day_close/mapper/BusinessDayCloseMapper.java
  src/main/java/com/kcc/banking/domain/business_day_close/service/BusinessDayCloseService.java
  src/main/java/com/kcc/banking/domain/trade/service/AccountTradeFacade.java
  src/main/java/com/kcc/banking/domain/trade/service/TradeService.java
  src/main/resources/mapper/businessDayCloseMapper.xml
  src/main/webapp/resources/js/page/account-open.js
Labels: ✨ Feature

#194 영업일 되돌리기 기능 구현
  src/main/java/com/kcc/banking/domain/account/dto/response/AccountDetailForInterest.java
  src/main/java/com/kcc/banking/domain/business_day/controller/BusinessDayRestController.java
  src/main/java/com/kcc/banking/domain/business_day/service/BusinessDayManagementFacade.java
  src/main/java/com/kcc/banking/domain/business_day/service/BusinessDayService.java
  src/main/java/com/kcc/banking/domain/business_day_close/mapper/BusinessDayCloseMapper.java
  src/main/java/com/kcc/banking/domain/business_day_close/service/BusinessDayCloseService.java
  src/main/java/com/kcc/banking/domain/common/service/CommonService.java
  src/main/java/com/kcc/banking/domain/interest/dto/request/InterestCreate.java
  src/main/java/com/kcc/banking/domain/interest/mapper/InterestMapper.java
  src/main/java/com/kcc/banking/domain/interest/service/InterestService.java
  src/main/resources/data.sql
  src/main/resources/mapper/accountMapper.xml
  src/main/resources/mapper/businessDayCloseMapper.xml
  src/main/resources/mapper/interestMapper.xml
  src/main/resources/schema.sql
  src/main/webapp/WEB-INF/views/business-day/business-day-management.jsp
  src/main/webapp/resources/js/modal/business-day-update-modal.js
  src/main/webapp/resources/js/page/business-day-management.js
Labels: ✨ Feature

#195 Feature/#188 bulk transfer UI
  src/main/java/com/kcc/banking/domain/trade/controller/TradeController.java
  src/main/webapp/WEB-INF/views/trade/bulk-transfer.jsp
  src/main/webapp/resources/css/page/bulk-transfer.css
Labels: ✨ Feature

#196 Feature/#188 bulk transfer UI
  src/main/webapp/WEB-INF/views/trade/bulk-transfer.jsp
  src/main/webapp/resources/css/page/bulk-transfer.css
Labels: ✨ Feature

#198 대량 이체 기능구현1(파일 다운로드 및 업로드, 등록)
  pom.xml
  src/main/java/com/kcc/banking/HelloController.java
  src/main/java/com/kcc/banking/domain/BulkTransferPreview.java
  src/main/java/com/kcc/banking/domain/bulk_transfer/controller/BulkTransferRestController.java
  src/main/java/com/kcc/banking/domain/bulk_transfer/dto/request/BulkTransferCreate.java
  src/main/java/com/kcc/banking/domain/bulk_transfer/mapper/BulkTransferMapper.java
  src/main/java/com/kcc/banking/domain/bulk_transfer/service/BulkTransferService.java
  src/main/java/com/kcc/banking/domain/trade/controller/TradeRestController.java
  src/main/java/com/kcc/banking/domain/trade/dto/request/TradeCreate.java
  src/main/java/com/kcc/banking/domain/trade/dto/request/TransferTradeCreate.java
  src/main/java/com/kcc/banking/domain/trade/service/AccountTradeFacade.java
  src/main/java/com/kcc/banking/domain/trade/service/TradeService.java
  src/main/resources/bulk-transfer-upload.xlsx
  src/main/resources/mapper/bulkTransferMapper.xml
  src/main/resources/mapper/tradeMapper.xml
  src/main/resources/schema.sql
  src/main/webapp/WEB-INF/views/employee-management.jsp
  src/main/webapp/resources/css/employee-management.css
  src/main/webapp/resources/js/employee-management.js
Labels: ✨ Feature

#199 Feature/#188 bulk transfer UI
  src/main/webapp/WEB-INF/views/trade/bulk-transfer.jsp
  src/main/webapp/resources/css/page/bulk-transfer.css
Labels: ✨ Feature

#200 행원 / 매니저 대시보드
  src/main/java/com/kcc/banking/domain/dashboard/controller/DashboardController.java
  src/main/java/com/kcc/banking/domain/dashboard/controller/DashboardRestController.java
  src/main/java/com/kcc/banking/domain/dashboard/dto/response/AccountOpenRatioChart.java
  src/main/java/com/kcc/banking/domain/dashboard/dto/response/DailyTransactionTypeChart.java
  src/main/java/com/kcc/banking/domain/dashboard/dto/response/DailyTransactionVolumeChart.java
  src/main/java/com/kcc/banking/domain/dashboard/dto/response/EmployeeTransactionVolumeChart.java
  src/main/java/com/kcc/banking/domain/dashboard/dto/response/MonthlyTransactionVolumeChart.java
  src/main/java/com/kcc/banking/domain/dashboard/dto/response/WeeklyTransactionVolumeChart.java
  src/main/java/com/kcc/banking/domain/dashboard/dto/response/YearlyTransactionComparisonChart.java
  src/main/java/com/kcc/banking/domain/dashboard/mapper/DashboardMapper.java
  src/main/java/com/kcc/banking/domain/dashboard/service/DashboardService.java
  src/main/java/com/kcc/banking/domain/interest/service/InterestService.java
  src/main/java/com/kcc/banking/domain/trade/service/AccountTradeFacade.java
  src/main/resources/data.sql
  src/main/resources/mapper/dashboardMapper.xml
  src/main/webapp/WEB-INF/views/account/account-close-cancel.jsp
  src/main/webapp/WEB-INF/views/account/account-close.jsp
  src/main/webapp/WEB-INF/views/account/account-open.jsp
  src/main/webapp/WEB-INF/views/account/account-update.jsp
  src/main/webapp/WEB-INF/views/business-day/business-day-management.jsp
  src/main/webapp/WEB-INF/views/business-day/employee-close.jsp
  src/main/webapp/WEB-INF/views/dashboard/employee-dashboard.jsp
  src/main/webapp/WEB-INF/views/dashboard/manager-dashboard.jsp
  src/main/webapp/WEB-INF/views/employee/employee-save.jsp
  src/main/webapp/WEB-INF/views/employee/employee-update.jsp
  src/main/webapp/WEB-INF/views/trade/account-transfer-cancel.jsp
  src/main/webapp/WEB-INF/views/trade/account-transfer.jsp
  src/main/webapp/WEB-INF/views/trade/cash-trade.jsp
  src/main/webapp/WEB-INF/views/trade/trade-list.jsp
  src/main/webapp/resources/components/modal/account-search-modal.jsp
  src/main/webapp/resources/components/modal/business-day-update-modal.jsp
  src/main/webapp/resources/components/modal/employee-detail-modal.jsp
  src/main/webapp/resources/css/header.css
  src/main/webapp/resources/css/styles.css
  src/main/webapp/resources/js/header.js
  src/main/webapp/resources/js/page/business-day-management.js
  src/main/webapp/resources/js/page/employee-close.js
  src/main/webapp/resources/js/page/employee-dashboard.js
  src/main/webapp/resources/js/page/manager-close.js
  src/main/webapp/resources/js/page/manager-dashboard.js
  src/main/webapp/resources/js/sidebar.js
Labels: ✨ Feature

#201 공통 색깔 및 버튼 수정
  src/main/webapp/WEB-INF/views/account/account-open.jsp
  src/main/webapp/WEB-INF/views/business-day/business-day-management.jsp
  src/main/webapp/WEB-INF/views/business-day/employee-close.jsp
  src/main/webapp/WEB-INF/views/employee/employee-update.jsp
  src/main/webapp/WEB-INF/views/trade/account-transfer-cancel.jsp
  src/main/webapp/WEB-INF/views/trade/account-transfer.jsp
  src/main/webapp/WEB-INF/views/trade/bulk-transfer.jsp
  src/main/webapp/WEB-INF/views/trade/cash-trade.jsp
  src/main/webapp/WEB-INF/views/trade/trade-list.jsp
  src/main/webapp/resources/components/modal/employee-search-modal.jsp
  src/main/webapp/resources/components/modal/search-modal-customer.jsp
  src/main/webapp/resources/css/deadline-management.css
  src/main/webapp/resources/css/header.css
  src/main/webapp/resources/css/sidebar.css
  src/main/webapp/resources/css/styles.css
  src/main/webapp/resources/js/sidebar.js
Labels: ✨ Feature

#202 계좌해지와 계좌해지 취소 CSS 변경
  src/main/webapp/WEB-INF/views/account/account-close-cancel.jsp
  src/main/webapp/WEB-INF/views/account/account-close.jsp
  src/main/webapp/resources/css/common-table.css
  src/main/webapp/resources/css/modal/account-search-modal.css
  src/main/webapp/resources/css/page/account-close.css
Labels: ♻️ Refactor

#205 Feature/#188 bulk transfer UI
  src/main/java/com/kcc/banking/domain/trade/controller/TradeController.java
  src/main/webapp/WEB-INF/views/trade/bulk-transfer-result.jsp
  src/main/webapp/WEB-INF/views/trade/bulk-transfer.jsp
  src/main/webapp/resources/css/page/bulk-transfer.css
  src/main/webapp/resources/js/page/bulk-transfer-result.js
  src/main/webapp/resources/js/page/bulk-transfer.js
Labels: ✨ Feature

#206 대시보드 리팩토링
  src/main/webapp/WEB-INF/views/business-day/manager-close.jsp
  src/main/webapp/WEB-INF/views/dashboard/employee-dashboard.jsp
  src/main/webapp/WEB-INF/views/dashboard/manager-dashboard.jsp
  src/main/webapp/resources/css/deadline-management.css
  src/main/webapp/resources/css/header.css
  src/main/webapp/resources/css/page/manager-dashboard.css
  src/main/webapp/resources/css/sidebar.css
  src/main/webapp/resources/css/styles.css
  src/main/webapp/resources/js/page/manager-dashboard.js
  src/main/webapp/resources/js/sidebar.js
Labels: ✨ Feature, ♻️ Refactor

#207 로그인 화면 변경
  src/main/webapp/WEB-INF/views/auth/login-form.jsp
  src/main/webapp/resources/css/signup.css
Labels: ♻️ Refactor

#209 대량이체 거래 결과 페이지 서버 연동
  src/main/java/com/kcc/banking/HelloController.java
  src/main/java/com/kcc/banking/domain/bulk_transfer/controller/BulkTransferController.java
  src/main/java/com/kcc/banking/domain/bulk_transfer/controller/BulkTransferRestController.java
  src/main/java/com/kcc/banking/domain/bulk_transfer/dto/response/BulkTransferDetail.java
  src/main/java/com/kcc/banking/domain/bulk_transfer/dto/response/BulkTransferPreview.java
  src/main/java/com/kcc/banking/domain/bulk_transfer/mapper/BulkTransferMapper.java
  src/main/java/com/kcc/banking/domain/bulk_transfer/service/BulkTransferService.java
  src/main/java/com/kcc/banking/domain/trade/controller/TradeController.java
  src/main/java/com/kcc/banking/domain/trade/controller/TradeRestController.java
  src/main/java/com/kcc/banking/domain/trade/dto/response/TradeByBulkTransfer.java
  src/main/java/com/kcc/banking/domain/trade/mapper/TradeMapper.java
  src/main/java/com/kcc/banking/domain/trade/service/TradeService.java
  src/main/resources/mapper/bulkTransferMapper.xml
  src/main/resources/mapper/tradeMapper.xml
  src/main/webapp/WEB-INF/views/trade/bulk-transfer-result.jsp
  src/main/webapp/WEB-INF/views/trade/bulk-transfer.jsp
  src/main/webapp/resources/js/page/bulk-transfer-result.js
  src/main/webapp/resources/js/sidebar.js
Labels: ✨ Feature

#213 대량 이체 성공 시 결과 페이지로 이동
  src/main/java/com/kcc/banking/domain/bulk_transfer/controller/BulkTransferRestController.java
  src/main/java/com/kcc/banking/domain/trade/controller/TradeController.java
  src/main/java/com/kcc/banking/domain/trade/service/AccountTradeFacade.java
  src/main/resources/mapper/bulkTransferMapper.xml
  src/main/resources/mapper/tradeMapper.xml
  src/main/webapp/WEB-INF/views/trade/bulk-transfer-result.jsp
  src/main/webapp/resources/css/page/bulk-transfer.css
  src/main/webapp/resources/css/styles.css
  src/main/webapp/resources/js/page/bulk-transfer.js
Labels: 🐛 BugFix, ✨ Feature

#215 예금주 조회 API구현
  src/main/java/com/kcc/banking/domain/bulk_transfer/controller/BulkTransferRestController.java
  src/main/java/com/kcc/banking/domain/bulk_transfer/dto/request/BulkTransferValidation.java
  src/main/java/com/kcc/banking/domain/bulk_transfer/dto/response/BulkTransferValidationResult.java
  src/main/java/com/kcc/banking/domain/trade/service/AccountTradeFacade.java
Labels: ✨ Feature

#216 행원별 거래 유형 비교 차트 추가 및 더미데이터 생성
  src/main/java/com/kcc/banking/common/init/InitData.java
  src/main/java/com/kcc/banking/domain/dashboard/controller/DashboardRestController.java
  src/main/java/com/kcc/banking/domain/dashboard/dto/response/EmployeeTransactionVolumeChart.java
  src/main/java/com/kcc/banking/domain/dashboard/dto/response/WeeklyTransactionVolumeChart.java
  src/main/java/com/kcc/banking/domain/dashboard/mapper/DashboardMapper.java
  src/main/java/com/kcc/banking/domain/dashboard/service/DashboardService.java
  src/main/resources/data.sql
  src/main/resources/mapper/dashboardMapper.xml
  src/main/webapp/WEB-INF/views/dashboard/manager-dashboard.jsp
  src/main/webapp/resources/js/page/manager-dashboard.js
Labels: ✨ Feature

#219 공통 CSS 수정
  src/main/java/com/kcc/banking/common/init/InitData.java
  src/main/resources/mapper/dashboardMapper.xml
  src/main/resources/schema.sql
  src/main/webapp/WEB-INF/views/auth/login-form.jsp
  src/main/webapp/WEB-INF/views/dashboard/manager-dashboard.jsp
  src/main/webapp/WEB-INF/views/employee/employee-save.jsp
  src/main/webapp/WEB-INF/views/trade/account-transfer.jsp
  src/main/webapp/resources/css/common-table.css
  src/main/webapp/resources/css/header.css
  src/main/webapp/resources/css/page/manager-dashboard.css
  src/main/webapp/resources/css/sidebar.css
  src/main/webapp/resources/css/signup.css
  src/main/webapp/resources/css/styles.css
  src/main/webapp/resources/js/page/manager-dashboard.js
Labels: ✨ Feature

#221 그라데이션 명도 변경 및 배경색 설정
  src/main/webapp/WEB-INF/views/account/account-close-cancel.jsp
  src/main/webapp/WEB-INF/views/account/account-open.jsp
  src/main/webapp/WEB-INF/views/employee/employee-list.jsp
  src/main/webapp/WEB-INF/views/employee/employee-update.jsp
  src/main/webapp/resources/components/modal/account-search-modal.jsp
  src/main/webapp/resources/css/common-table.css
  src/main/webapp/resources/css/header.css
  src/main/webapp/resources/css/sidebar.css
  src/main/webapp/resources/css/styles.css
Labels: ♻️ Refactor

#222 예금주 확인 기능 API 연동
  src/main/java/com/kcc/banking/domain/bulk_transfer/controller/BulkTransferRestController.java
  src/main/java/com/kcc/banking/domain/bulk_transfer/dto/request/BulkTransferValidation.java
  src/main/java/com/kcc/banking/domain/bulk_transfer/dto/response/BulkTransferValidationResult.java
  src/main/java/com/kcc/banking/domain/trade/service/AccountTradeFacade.java
  src/main/webapp/WEB-INF/views/trade/bulk-transfer-result.jsp
  src/main/webapp/WEB-INF/views/trade/bulk-transfer.jsp
  src/main/webapp/WEB-INF/views/trade/trade-list.jsp
  src/main/webapp/resources/css/page/bulk-transfer.css
  src/main/webapp/resources/css/page/trade-list.css
  src/main/webapp/resources/js/page/bulk-transfer-result.js
  src/main/webapp/resources/js/page/bulk-transfer.js
  src/main/webapp/resources/js/page/trade-list.js
Labels: 🐛 BugFix, ✨ Feature, ♻️ Refactor

#224 매니저 대시보드 UI 및 기능 구현
  src/main/java/com/kcc/banking/domain/dashboard/dto/response/WeeklyTransactionVolumeChart.java
  src/main/resources/mapper/dashboardMapper.xml
  src/main/webapp/WEB-INF/views/auth/login-form.jsp
  src/main/webapp/WEB-INF/views/dashboard/manager-dashboard.jsp
  src/main/webapp/resources/css/header.css
  src/main/webapp/resources/css/page/manager-dashboard.css
  src/main/webapp/resources/css/sidebar.css
  src/main/webapp/resources/js/page/manager-dashboard.js
Labels: ✨ Feature

#231 Feature/#188 bulk transfer UI
  src/main/webapp/WEB-INF/views/trade/bulk-transfer.jsp
  src/main/webapp/resources/js/page/bulk-transfer.js
Labels: 🐛 BugFix

#232 Feature/#188 bulk transfer UI
  src/main/resources/schema.sql
  src/main/webapp/WEB-INF/views/trade/bulk-transfer.jsp
  src/main/webapp/resources/css/page/bulk-transfer.css
  src/main/webapp/resources/js/page/bulk-transfer.js
Labels: ✨ Feature

#234 적금 사이드바 연결
  src/main/webapp/resources/js/sidebar.js
Labels: ♻️ Refactor

#235 Feature/#188 bulk transfer UI
  src/main/webapp/WEB-INF/views/trade/bulk-transfer.jsp
  src/main/webapp/resources/js/page/bulk-transfer.js
Labels: ✨ Feature

#237 엔터키로 계좌 조회 추가
  src/main/webapp/WEB-INF/views/dashboard/employee-dashboard.jsp
  src/main/webapp/resources/css/page/employee-dashboard.css
  src/main/webapp/resources/js/modal/account-search-modal.js
Labels: ♻️ Refactor

#242 공통 모달 CSS 수정
  src/main/java/com/kcc/banking/common/auth/SecurityConfig.java
  src/main/webapp/resources/components/modal/account-search-modal.jsp
  src/main/webapp/resources/css/modal/account-search-modal.css
  src/main/webapp/resources/css/styles.css
Labels: ♻️ Refactor

#243 계좌 검색 모달, 고객 검색 모달 수정
  src/main/webapp/resources/components/modal/account-search-modal.jsp
  src/main/webapp/resources/components/modal/employee-search-modal.jsp
  src/main/webapp/resources/components/modal/search-modal-customer.jsp
  src/main/webapp/resources/css/modal/account-search-modal.css
  src/main/webapp/resources/css/modal/search-modal-customer.css
  src/main/webapp/resources/css/styles.css
  src/main/webapp/resources/js/modal/account-search-modal.js
  src/main/webapp/resources/js/modal/search-customer-modal.js
Labels: ♻️ Refactor

#244 Feature/#188 bulk transfer UI
  src/main/java/com/kcc/banking/domain/bulk_transfer/controller/BulkTransferRestController.java
  src/main/webapp/WEB-INF/views/trade/bulk-transfer-result.jsp
  src/main/webapp/WEB-INF/views/trade/bulk-transfer.jsp
  src/main/webapp/resources/js/page/bulk-transfer.js
Labels: ✨ Feature

#245 거래내역 목록 조회 페이지 수정
  src/main/webapp/WEB-INF/views/trade/trade-list.jsp
  src/main/webapp/resources/css/page/trade-list.css
Labels: ♻️ Refactor

#246 행원관리 UI 수정
  src/main/java/com/kcc/banking/domain/employee/controller/EmployeeRestController.java
  src/main/resources/mapper/employeeMapper.xml
  src/main/webapp/WEB-INF/views/employee/employee-list.jsp
  src/main/webapp/resources/components/modal/employee-search-modal.jsp
  src/main/webapp/resources/css/modal/employee-search-modal.css
  src/main/webapp/resources/js/modal/employee-search-modal.js
Labels: ♻️ Refactor

#248 Feature/#188 bulk transfer UI
  src/main/resources/mapper/tradeMapper.xml
  src/main/webapp/WEB-INF/views/trade/bulk-transfer-result.jsp
  src/main/webapp/resources/js/page/bulk-transfer-result.js
Labels: ✨ Feature

#253 마감 영업일 관리 헤더 사이드바 통합
  src/main/webapp/resources/js/header.js
  src/main/webapp/resources/js/sidebar.js
Labels: ♻️ Refactor

#254 Feature/#249 bulk transfer add indivisual
  src/main/webapp/WEB-INF/views/trade/bulk-transfer-result.jsp
  src/main/webapp/WEB-INF/views/trade/bulk-transfer.jsp
  src/main/webapp/resources/js/page/bulk-transfer-result.js
  src/main/webapp/resources/js/page/bulk-transfer.js
Labels: ✨ Feature

#255 Feature/#249 bulk transfer add indivisual
  src/main/webapp/resources/js/page/bulk-transfer-result.js
Labels: ✨ Feature

#256 매니저 마감관리 수정
  src/main/java/com/kcc/banking/domain/business_day_close/dto/response/ManagerClosingData.java
  src/main/java/com/kcc/banking/domain/business_day_close/service/BusinessDayCloseService.java
  src/main/webapp/WEB-INF/views/business-day/manager-close.jsp
  src/main/webapp/resources/css/deadline-management.css
Labels: ♻️ Refactor

#258 Feature/#249 bulk transfer add indivisual
  src/main/webapp/WEB-INF/views/trade/bulk-transfer-result.jsp
  src/main/webapp/resources/js/page/bulk-transfer-result.js
Labels: ✨ Feature

#260 Feature/#259 bulk transfer registration page error fix
  src/main/webapp/WEB-INF/views/trade/bulk-transfer.jsp
  src/main/webapp/resources/js/page/bulk-transfer.js
Labels: ✨ Feature

#261 Feature/#247 account
  src/main/webapp/WEB-INF/views/account/account-open.jsp
  src/main/webapp/resources/components/modal/search-modal-customer.jsp
  src/main/webapp/resources/css/common-table.css
  src/main/webapp/resources/css/page/account-open.css
  src/main/webapp/resources/js/modal/search-customer-modal.js
  src/main/webapp/resources/js/page/account-open.js
Labels: ♻️ Refactor

#266 예금상품 조회 기능 구현
  src/main/java/com/kcc/banking/domain/account/controller/AccountRestController.java
  src/main/java/com/kcc/banking/domain/account/mapper/AccountMapper.java
  src/main/java/com/kcc/banking/domain/account/service/AccountService.java
  src/main/java/com/kcc/banking/domain/customer/dto/response/CustomerSearchInfo.java
  src/main/java/com/kcc/banking/domain/product/controller/ProductRestController.java
  src/main/java/com/kcc/banking/domain/product/dto/request/ProductSearch.java
  src/main/java/com/kcc/banking/domain/product/dto/response/ProductDetail.java
  src/main/java/com/kcc/banking/domain/product/mapper/ProductMapper.java
  src/main/java/com/kcc/banking/domain/product/service/ProductService.java
  src/main/resources/mapper/accountMapper.xml
  src/main/resources/mapper/customerMapper.xml
  src/main/resources/mapper/productMapper.xml
  src/main/webapp/WEB-INF/views/account/account-open.jsp
  src/main/webapp/resources/components/modal/search-modal-customer.jsp
  src/main/webapp/resources/components/modal/search-modal-deposit-product.jsp
  src/main/webapp/resources/css/modal/search-modal-customer.css
  src/main/webapp/resources/css/modal/search-modal-deposit-product.css
  src/main/webapp/resources/js/modal/deposit-product-search-modal.js
  src/main/webapp/resources/js/modal/search-customer-modal.js
  src/main/webapp/resources/js/page/account-open.js
Labels: ✨ Feature

#267 계좌 개설 컬럼 추가에 따른 수정작업
  src/main/java/com/kcc/banking/domain/account/controller/AccountRestController.java
  src/main/java/com/kcc/banking/domain/account/dto/request/AccountCreate.java
  src/main/java/com/kcc/banking/domain/account/dto/request/AccountOpen.java
  src/main/java/com/kcc/banking/domain/account/dto/response/AccountOpenResultOfModal.java
  src/main/java/com/kcc/banking/domain/account/service/AccountService.java
  src/main/resources/mapper/accountMapper.xml
  src/main/webapp/resources/components/modal/result-modal-open-account.jsp
  src/main/webapp/resources/css/common-table.css
  src/main/webapp/resources/css/modal/result-modal-open-account.css
  src/main/webapp/resources/js/modal/deposit-product-search-modal.js
  src/main/webapp/resources/js/page/account-open.js
Labels: ♻️ Refactor

#269 계좌이체 UI변경
  src/main/webapp/WEB-INF/views/trade/account-transfer.jsp
  src/main/webapp/resources/assets/timer.jpg
  src/main/webapp/resources/css/page/account-transfer.css
  src/main/webapp/resources/js/page/account-transfer.js
Labels: ♻️ Refactor

#270 매니저 금일 마감금액 변경
  src/main/java/com/kcc/banking/domain/business_day_close/controller/BusinessDayCloseController.java
  src/main/java/com/kcc/banking/domain/business_day_close/dto/response/ManagerClosingData.java
  src/main/java/com/kcc/banking/domain/business_day_close/service/BusinessDayCloseService.java
  src/main/webapp/WEB-INF/views/business-day/business-day-management.jsp
  src/main/webapp/WEB-INF/views/business-day/manager-close.jsp
  src/main/webapp/resources/css/deadline-management.css
  src/main/webapp/resources/js/page/manager-close.js
Labels: ♻️ Refactor

#272 공통 테이블 css변경
  src/main/webapp/resources/css/common-table.css
Labels: ✨ Feature

#273 common-table th 의 min-width: 10%
  src/main/webapp/WEB-INF/views/business-day/business-day-management.jsp
  src/main/webapp/resources/css/common-table.css
Labels: ♻️ Refactor

#276 매니저 마감 vaultCash 수정
  src/main/java/com/kcc/banking/domain/business_day/service/BusinessDayManagementFacade.java
  src/main/java/com/kcc/banking/domain/business_day_close/dto/response/ManagerClosingData.java
  src/main/webapp/WEB-INF/views/business-day/manager-close.jsp
  src/main/webapp/resources/css/deadline-management.css
  src/main/webapp/resources/js/page/manager-close.js
Labels: ♻️ Refactor

#277 행원 마감 페이지 수정 & no-margin 공통 처리
  src/main/webapp/WEB-INF/views/business-day/employee-close.jsp
  src/main/webapp/WEB-INF/views/business-day/manager-close.jsp
  src/main/webapp/resources/css/deadline-management.css
  src/main/webapp/resources/css/modal/account-search-modal.css
  src/main/webapp/resources/css/modal/businessday-update-modal.css
  src/main/webapp/resources/css/modal/search-modal-customer.css
  src/main/webapp/resources/css/styles.css
Labels: ♻️ Refactor

#278 현금입출금 UI수정
  src/main/java/com/kcc/banking/domain/account/controller/AccountController.java
  src/main/java/com/kcc/banking/domain/trade/controller/TradeController.java
  src/main/webapp/WEB-INF/views/account/account-open.jsp
  src/main/webapp/WEB-INF/views/trade/account-transfer.jsp
  src/main/webapp/WEB-INF/views/trade/cash-trade.jsp
  src/main/webapp/resources/css/page/account-open.css
  src/main/webapp/resources/css/page/account-transfer.css
  src/main/webapp/resources/css/page/trade-cash.css
  src/main/webapp/resources/js/page/account-transfer.js
  src/main/webapp/resources/js/page/trade-cash.js
  src/main/webapp/resources/js/sidebar.js
Labels: ♻️ Refactor

#280 행원 마감 JS 수정
  src/main/java/com/kcc/banking/domain/business_day/service/BusinessDayManagementFacade.java
  src/main/java/com/kcc/banking/domain/business_day_close/dto/response/ClosingData.java
  src/main/java/com/kcc/banking/domain/business_day_close/dto/response/EmployeeClosingData.java
  src/main/webapp/WEB-INF/views/business-day/employee-close.jsp
  src/main/webapp/resources/css/deadline-management.css
  src/main/webapp/resources/js/footer.js
  src/main/webapp/resources/js/page/employee-close.js
Labels: ♻️ Refactor

#281 입출금 UI및 JS 리팩토링
  src/main/java/com/kcc/banking/domain/trade/controller/TradeController.java
  src/main/webapp/WEB-INF/views/account/account-open.jsp
  src/main/webapp/WEB-INF/views/trade/account-transfer.jsp
  src/main/webapp/WEB-INF/views/trade/cash-trade.jsp
  src/main/webapp/resources/css/page/account-open.css
  src/main/webapp/resources/css/page/account-transfer.css
  src/main/webapp/resources/css/page/trade-cash.css
  src/main/webapp/resources/js/modal/search-customer-modal.js
  src/main/webapp/resources/js/page/account-open.js
  src/main/webapp/resources/js/page/account-transfer.js
  src/main/webapp/resources/js/page/trade-cash.js
Labels: ♻️ Refactor

#282 행원 마감 UI 변경
  src/main/webapp/WEB-INF/views/business-day/employee-close.jsp
  src/main/webapp/resources/css/deadline-management.css
Labels: ✨ Feature

#286 이체한도 UI 및 스크립트 작성
  src/main/java/com/kcc/banking/domain/account/controller/AccountRestController.java
  src/main/java/com/kcc/banking/domain/account/dto/response/AccountOfModal.java
  src/main/java/com/kcc/banking/domain/account/dto/response/AccountOpenResultOfModal.java
  src/main/java/com/kcc/banking/domain/trade/controller/TradeRestController.java
  src/main/java/com/kcc/banking/domain/trade/dto/request/TradeSearch.java
  src/main/java/com/kcc/banking/domain/trade/mapper/TradeMapper.java
  src/main/java/com/kcc/banking/domain/trade/service/AccountTradeFacade.java
  src/main/java/com/kcc/banking/domain/trade/service/TradeService.java
  src/main/resources/data.sql
  src/main/resources/mapper/accountMapper.xml
  src/main/resources/mapper/tradeMapper.xml
  src/main/webapp/WEB-INF/views/account/account-open.jsp
  src/main/webapp/WEB-INF/views/trade/account-transfer.jsp
  src/main/webapp/resources/css/page/account-open.css
  src/main/webapp/resources/css/page/account-transfer.css
  src/main/webapp/resources/js/page/account-open.js
  src/main/webapp/resources/js/page/account-transfer.js
Labels: ✨ Feature, ♻️ Refactor

#289 영업일 업데이트 모달 수정 및 기능 추가 완료
  src/main/java/com/kcc/banking/domain/business_day_close/controller/BusinessDayCloseRestController.java
  src/main/java/com/kcc/banking/domain/business_day_close/dto/response/ClosingData.java
  src/main/java/com/kcc/banking/domain/business_day_close/dto/response/ManagerClosingData.java
  src/main/java/com/kcc/banking/domain/business_day_close/service/BusinessDayCloseService.java
  src/main/resources/data.sql
  src/main/resources/mapper/businessDayCloseMapper.xml
  src/main/webapp/WEB-INF/views/business-day/business-day-management.jsp
  src/main/webapp/WEB-INF/views/business-day/manager-close.jsp
  src/main/webapp/resources/components/modal/business-day-update-modal.jsp
  src/main/webapp/resources/css/deadline-management.css
  src/main/webapp/resources/css/modal/businessday-update-modal.css
  src/main/webapp/resources/css/page/business-day-management.css
  src/main/webapp/resources/js/footer.js
  src/main/webapp/resources/js/modal/business-day-update-modal.js
Labels: ✨ Feature, ♻️ Refactor

#288 Feature/#284 bulk transfer receipt service
  src/main/java/com/kcc/banking/domain/bulk_transfer/controller/BulkTransferRestController.java
  src/main/java/com/kcc/banking/domain/bulk_transfer/dto/request/BulkTransferUpdate.java
  src/main/java/com/kcc/banking/domain/bulk_transfer/dto/response/BulkTransferDetail.java
  src/main/java/com/kcc/banking/domain/bulk_transfer/service/BulkTransferService.java
  src/main/java/com/kcc/banking/domain/trade/dto/request/TransferTradeUpdate.java
  src/main/java/com/kcc/banking/domain/trade/service/AccountTradeFacade.java
  src/main/resources/mapper/bulkTransferMapper.xml
Labels: ✨ Feature

#292 이체한도 기능 추가에 따른 예외처리 및 테스트 작성
  pom.xml
  src/main/java/com/kcc/banking/common/exception/ErrorCode.java
  src/main/java/com/kcc/banking/domain/account/dto/response/AccountDetail.java
  src/main/java/com/kcc/banking/domain/customer/dto/request/CustomerCreate.java
  src/main/java/com/kcc/banking/domain/customer/mapper/CustomerMapper.java
  src/main/java/com/kcc/banking/domain/customer/service/CustomerService.java
  src/main/java/com/kcc/banking/domain/trade/service/AccountTradeFacade.java
  src/main/resources/mapper/accountMapper.xml
  src/main/resources/mapper/customerMapper.xml
  src/main/resources/schema.sql
  src/main/webapp/resources/js/page/trade-cash.js
  src/test/java/com/kcc/banking/IntegrationTest.java
  src/test/java/com/kcc/banking/domain/trade/controller/TradeRestControllerTest.java
  src/test/resources/test-data.sql
Labels: ✨ Feature, ✅ Test

#294 출금 시 사원 마감 테이블 상태 변경 버그 수정
  src/main/java/com/kcc/banking/domain/business_day_close/service/BusinessDayCloseService.java
Labels: 🐛 BugFix

#297 영업일 변경시 지점 시재금 변경
  src/main/webapp/resources/js/modal/business-day-update-modal.js
Labels: 🐛 BugFix

#300 매니저 마감 및 영업일 변경 시 시재금 분배 수정
  src/main/java/com/kcc/banking/domain/branch/controller/DashboardController.java
  src/main/java/com/kcc/banking/domain/branch/controller/DashboardRestController.java
  src/main/java/com/kcc/banking/domain/branch/dto/response/AccountOpenRatioChart.java
  src/main/java/com/kcc/banking/domain/branch/dto/response/DailyTransactionTypeChart.java
  src/main/java/com/kcc/banking/domain/branch/dto/response/DailyTransactionVolumeChart.java
  src/main/java/com/kcc/banking/domain/branch/dto/response/EmployeeTransactionVolumeChart.java
  src/main/java/com/kcc/banking/domain/branch/dto/response/MonthlyTransactionVolumeChart.java
  src/main/java/com/kcc/banking/domain/branch/dto/response/WeeklyTransactionVolumeChart.java
  src/main/java/com/kcc/banking/domain/branch/dto/response/YearlyTransactionComparisonChart.java
  src/main/java/com/kcc/banking/domain/branch/mapper/DashboardMapper.java
  src/main/java/com/kcc/banking/domain/branch/service/DashboardService.java
  src/main/java/com/kcc/banking/domain/business_day/dto/request/BusinessDayChange.java
  src/main/java/com/kcc/banking/domain/business_day_close/dto/request/BranchClosingCreate.java
  src/main/java/com/kcc/banking/domain/business_day_close/service/BusinessDayCloseService.java
  src/main/resources/data.sql
  src/main/resources/mapper/businessDayCloseMapper.xml
  src/main/resources/mapper/dashboardMapper.xml
  src/main/resources/schema.sql
  src/main/webapp/WEB-INF/views/employee-management.jsp
  src/main/webapp/resources/components/modal/business-day-update-modal.jsp
  src/main/webapp/resources/js/modal/business-day-update-modal.js
Labels: ✨ Feature

#302 매니저 마감 변경
  src/main/java/com/kcc/banking/domain/account/service/AccountService.java
  src/main/java/com/kcc/banking/domain/business_day/dto/request/BusinessDayChange.java
  src/main/java/com/kcc/banking/domain/business_day_close/dto/request/BranchClosingCreate.java
  src/main/java/com/kcc/banking/domain/business_day_close/service/BusinessDayCloseService.java
  src/main/java/com/kcc/banking/domain/dashboard/controller/DashboardController.java
  src/main/java/com/kcc/banking/domain/dashboard/controller/DashboardRestController.java
  src/main/java/com/kcc/banking/domain/dashboard/dto/response/AccountOpenRatioChart.java
  src/main/java/com/kcc/banking/domain/dashboard/dto/response/DailyTransactionTypeChart.java
  src/main/java/com/kcc/banking/domain/dashboard/dto/response/DailyTransactionVolumeChart.java
  src/main/java/com/kcc/banking/domain/dashboard/dto/response/EmployeeTransactionVolumeChart.java
  src/main/java/com/kcc/banking/domain/dashboard/dto/response/MonthlyTransactionVolumeChart.java
  src/main/java/com/kcc/banking/domain/dashboard/dto/response/WeeklyTransactionVolumeChart.java
  src/main/java/com/kcc/banking/domain/dashboard/dto/response/YearlyTransactionComparisonChart.java
  src/main/java/com/kcc/banking/domain/dashboard/mapper/DashboardMapper.java
  src/main/java/com/kcc/banking/domain/dashboard/service/DashboardService.java
  src/main/resources/data.sql
  src/main/resources/mapper/businessDayCloseMapper.xml
  src/main/resources/mapper/dashboardMapper.xml
  src/main/resources/schema.sql
  src/main/webapp/resources/components/modal/business-day-update-modal.jsp
  src/main/webapp/resources/components/modal/trade-cash-result-modal.jsp
  src/main/webapp/resources/js/modal/business-day-update-modal.js
  src/main/webapp/resources/js/modal/transfer-result-modal.js
  src/main/webapp/resources/js/page/trade-cash.js
Labels: ✨ Feature

#305 행원 간 현금 거래 내역 테이블 추가 및 더미데이터 추가
  src/main/resources/data.sql
  src/main/resources/schema.sql
Labels: ✨ Feature

#308 동시성 테스트 초안 작성
  src/main/java/com/kcc/banking/common/config/AsyncConfig.java
  src/main/java/com/kcc/banking/common/exception/GlobalExceptionHandler.java
  src/main/java/com/kcc/banking/common/init/InitData.java
  src/main/resources/mapper/accountMapper.xml
  src/test/java/com/kcc/banking/domain/trade/controller/TradeRestControllerTest.java
  src/test/resources/test-data.sql
  src/test/resources/test-schema.sql
Labels: 🛠 Setting, ✅ Test

#309 행원 마감에 인수도 거래 추가
  src/main/java/com/kcc/banking/domain/business_day/service/BusinessDayManagementFacade.java
  src/main/java/com/kcc/banking/domain/business_day_close/dto/response/EmployeeClosingData.java
  src/main/java/com/kcc/banking/domain/cash_exchange/controller/CashExchangeController.java
  src/main/java/com/kcc/banking/domain/cash_exchange/controller/CashExchangeRestController.java
  src/main/java/com/kcc/banking/domain/cash_exchange/dto/response/CashExchangeData.java
  src/main/java/com/kcc/banking/domain/cash_exchange/mapper/CashExchangeMapper.java
  src/main/java/com/kcc/banking/domain/cash_exchange/service/CashExchangeService.java
  src/main/resources/data.sql
  src/main/resources/mapper/CashExchangeMapper.xml
  src/main/resources/schema.sql
  src/main/webapp/WEB-INF/views/business-day/employee-close.jsp
  src/main/webapp/WEB-INF/views/cash-exchange/cash-exchange-close.jsp
  src/main/webapp/WEB-INF/views/cash-exchange/cash-exchange.jsp
  src/main/webapp/resources/js/page/employee-close.js
  src/main/webapp/resources/js/sidebar.js
Labels: ✨ Feature

#311 데드락 해결
  pom.xml
  src/main/java/com/kcc/banking/MicroBankingSystemApplication.java
  src/main/java/com/kcc/banking/common/init/InitData.java
  src/main/java/com/kcc/banking/domain/account/service/AccountService.java
  src/main/java/com/kcc/banking/domain/trade/controller/TradeRestController.java
  src/main/java/com/kcc/banking/domain/trade/service/AccountTradeFacade.java
  src/test/java/com/kcc/banking/domain/trade/controller/TradeRestControllerTest.java
Labels: ✨ Feature, ✅ Test

#313 취소거래 API연결
  src/main/java/com/kcc/banking/domain/trade/controller/TradeRestController.java
  src/main/java/com/kcc/banking/domain/trade/dto/response/TradeOfList.java
  src/main/java/com/kcc/banking/domain/trade/mapper/TradeMapper.java
  src/main/java/com/kcc/banking/domain/trade/service/TradeService.java
  src/main/resources/mapper/tradeMapper.xml
  src/main/webapp/resources/components/modal/result-modal-open-account.jsp
  src/main/webapp/resources/js/modal/account-open-result-modal.js
  src/main/webapp/resources/js/page/trade-list.js
Labels: ✨ Feature

#314 매니저 시재금 마감 추가
  src/main/java/com/kcc/banking/domain/business_day_close/dto/response/EmployeeClosingData.java
  src/main/java/com/kcc/banking/domain/cash_exchange/controller/CashExchangeController.java
  src/main/java/com/kcc/banking/domain/cash_exchange/dto/response/CashExchangeCloseData.java
  src/main/java/com/kcc/banking/domain/cash_exchange/dto/response/CashExchangeData.java
  src/main/java/com/kcc/banking/domain/cash_exchange/mapper/CashExchangeMapper.java
  src/main/java/com/kcc/banking/domain/cash_exchange/service/CashExchangeService.java
  src/main/resources/data.sql
  src/main/resources/mapper/CashExchangeMapper.xml
  src/main/webapp/WEB-INF/views/business-day/employee-close.jsp
  src/main/webapp/WEB-INF/views/business-day/manager-close.jsp
  src/main/webapp/WEB-INF/views/cash-exchange/cash-exchange-close.jsp
  src/main/webapp/resources/css/deadline-management.css
  src/main/webapp/resources/js/page/cash-exchange-close.js
Labels: ✨ Feature

#317 매니저 시재금 마감 완료
  src/main/java/com/kcc/banking/common/exception/ErrorCode.java
  src/main/java/com/kcc/banking/domain/cash_exchange/controller/CashExchangeRestController.java
  src/main/java/com/kcc/banking/domain/cash_exchange/dto/request/ManagerCashBalanceRequest.java
  src/main/java/com/kcc/banking/domain/cash_exchange/service/CashExchangeService.java
  src/main/webapp/WEB-INF/views/business-day/manager-close.jsp
  src/main/webapp/WEB-INF/views/cash-exchange/cash-exchange-close.jsp
  src/main/webapp/resources/components/modal/business-day-update-modal.jsp
  src/main/webapp/resources/js/modal/business-day-update-modal.js
  src/main/webapp/resources/js/page/cash-exchange-close.js
  src/main/webapp/resources/js/page/employee-close.js
Labels: ✨ Feature

#320 OTP API 연동 초기설정
  pom.xml
  src/main/java/com/kcc/banking/common/otp/OtpController.java
  src/main/java/com/kcc/banking/common/otp/OtpResultServlet.java
  src/main/java/com/kcc/banking/common/otp/OtpServlet.java
  src/main/webapp/WEB-INF/views/otp-test.jsp
Labels: ✨ Feature

#322 sms 인증 구현
  pom.xml
  src/main/java/com/kcc/banking/common/exception/ErrorCode.java
  src/main/java/com/kcc/banking/common/sms/CoolSmsRestController.java
  src/main/java/com/kcc/banking/common/sms/CoolSmsService.java
  src/main/java/com/kcc/banking/common/sms/PhoneNumber.java
Labels: ✨ Feature

#325 매니저 인수도거래 UI 구현 / 인도 거래 구현
  src/main/java/com/kcc/banking/domain/business_day/controller/BusinessDayRestController.java
  src/main/java/com/kcc/banking/domain/business_day/service/BusinessDayManagementFacade.java
  src/main/java/com/kcc/banking/domain/business_day_close/dto/request/EmployeeAdditionalUpdate.java
  src/main/java/com/kcc/banking/domain/business_day_close/mapper/BusinessDayCloseMapper.java
  src/main/java/com/kcc/banking/domain/cash_exchange/controller/CashExchangeController.java
  src/main/java/com/kcc/banking/domain/cash_exchange/controller/CashExchangeRestController.java
  src/main/java/com/kcc/banking/domain/cash_exchange/dto/request/CashExchangeCreate.java
  src/main/java/com/kcc/banking/domain/cash_exchange/dto/request/ManagerCashBalance.java
  src/main/java/com/kcc/banking/domain/cash_exchange/dto/response/EmployeeDataResponse.java
  src/main/java/com/kcc/banking/domain/cash_exchange/mapper/CashExchangeMapper.java
  src/main/java/com/kcc/banking/domain/cash_exchange/service/CashExchangeService.java
  src/main/resources/data.sql
  src/main/resources/mapper/CashExchangeMapper.xml
  src/main/resources/mapper/businessDayCloseMapper.xml
  src/main/resources/schema.sql
  src/main/webapp/WEB-INF/views/cash-exchange/cash-exchange-close.jsp
  src/main/webapp/WEB-INF/views/cash-exchange/cash-exchange.jsp
  src/main/webapp/resources/components/modal/cash-exchange-result-modal.jsp
  src/main/webapp/resources/components/modal/employee-search-modal.jsp
  src/main/webapp/resources/css/page/cash-exchange.css
  src/main/webapp/resources/js/modal/employee-search-modal.js
  src/main/webapp/resources/js/page/cash-exchange.js
  src/main/webapp/resources/js/page/employee-update.js
Labels: ✨ Feature

#326 고객 등록 기능 구현
  src/main/java/com/kcc/banking/domain/customer/controller/CustomerController.java
  src/main/java/com/kcc/banking/domain/customer/controller/CustomerRestController.java
  src/main/java/com/kcc/banking/domain/customer/dto/request/CustomerCreate.java
  src/main/java/com/kcc/banking/domain/customer/dto/response/CreatedCustomer.java
  src/main/java/com/kcc/banking/domain/customer/service/CustomerService.java
  src/main/resources/mapper/customerMapper.xml
  src/main/resources/schema.sql
  src/main/webapp/WEB-INF/views/customer/customer-save.jsp
  src/main/webapp/WEB-INF/views/customer/employee-list.jsp
  src/main/webapp/WEB-INF/views/customer/employee-update.jsp
  src/main/webapp/resources/components/modal/customer-detail-modal.jsp
  src/main/webapp/resources/css/modal/customer-detail-modal.css
  src/main/webapp/resources/css/page/customer-save.css
  src/main/webapp/resources/js/header.js
  src/main/webapp/resources/js/modal/customer-detail-modal.js
  src/main/webapp/resources/js/page/customer-save.js
  src/main/webapp/resources/js/sidebar.js
Labels: ✨ Feature

#328 누락 컬럼 추가 및 마스킹 처리
  src/main/webapp/WEB-INF/views/customer/customer-save.jsp
  src/main/webapp/resources/components/modal/customer-detail-modal.jsp
  src/main/webapp/resources/css/page/customer-save.css
  src/main/webapp/resources/js/page/customer-save.js
Labels: ♻️ Refactor

#330 고객 목록 기능 구현
  pom.xml
  src/main/java/com/kcc/banking/domain/customer/controller/CustomerController.java
  src/main/java/com/kcc/banking/domain/customer/controller/CustomerRestController.java
  src/main/java/com/kcc/banking/domain/customer/dto/request/CustomerSearch.java
  src/main/java/com/kcc/banking/domain/customer/dto/response/CustomerSearchDTO.java
  src/main/java/com/kcc/banking/domain/customer/dto/response/CustomerSearchInfo.java
  src/main/java/com/kcc/banking/domain/customer/dto/response/CustomerSearchResult.java
  src/main/java/com/kcc/banking/domain/customer/mapper/CustomerMapper.java
  src/main/java/com/kcc/banking/domain/customer/service/CustomerService.java
  src/main/java/com/kcc/banking/domain/trade/dto/response/PageDTO.java
  src/main/resources/mapper/customerMapper.xml
  src/main/resources/mapper/tradeMapper.xml
  src/main/webapp/WEB-INF/views/customer/customer-list.jsp
  src/main/webapp/WEB-INF/views/customer/employee-list.jsp
  src/main/webapp/resources/components/modal/search-modal-customer.jsp
  src/main/webapp/resources/css/page/customer-list.css
  src/main/webapp/resources/js/header.js
  src/main/webapp/resources/js/modal/search-customer-modal.js
  src/main/webapp/resources/js/page/customer-list.js
  src/test/java/com/kcc/banking/domain/trade/controller/TradeRestControllerTest.java
Labels: ✨ Feature

#332 거래목록 CSS변경
  src/main/java/com/kcc/banking/domain/customer/dto/response/CustomerSearchInfo.java
  src/main/resources/mapper/customerMapper.xml
  src/main/webapp/WEB-INF/views/customer/customer-list.jsp
  src/main/webapp/WEB-INF/views/trade/trade-list.jsp
  src/main/webapp/resources/css/page/customer-list.css
  src/main/webapp/resources/css/page/trade-list.css
  src/main/webapp/resources/css/styles.css
  src/main/webapp/resources/js/page/customer-list.js
  src/main/webapp/resources/js/page/trade-list.js
Labels: ♻️ Refactor

#336 매니저 및 행원 마감 시 페이지 오버레이
  src/main/java/com/kcc/banking/domain/business_day_close/controller/BusinessDayCloseRestController.java
  src/main/webapp/WEB-INF/views/account/account-close-cancel.jsp
  src/main/webapp/WEB-INF/views/account/account-close.jsp
  src/main/webapp/WEB-INF/views/account/account-open.jsp
  src/main/webapp/WEB-INF/views/account/account-update.jsp
  src/main/webapp/WEB-INF/views/business-day/employee-close.jsp
  src/main/webapp/WEB-INF/views/cash-exchange/cash-exchange.jsp
  src/main/webapp/WEB-INF/views/trade/account-transfer-cancel.jsp
  src/main/webapp/WEB-INF/views/trade/account-transfer.jsp
  src/main/webapp/WEB-INF/views/trade/bulk-transfer.jsp
  src/main/webapp/WEB-INF/views/trade/cash-trade.jsp
  src/main/webapp/resources/components/close-overlay.jsp
  src/main/webapp/resources/css/styles.css
  src/main/webapp/resources/js/footer.js
  src/main/webapp/resources/js/page/account-close-cancel.js
  src/main/webapp/resources/js/page/account-close.js
  src/main/webapp/resources/js/page/account-open.js
  src/main/webapp/resources/js/page/account-transfer-cancel.js
  src/main/webapp/resources/js/page/account-transfer.js
  src/main/webapp/resources/js/page/bulk-transfer.js
  src/main/webapp/resources/js/page/cash-exchange-close.js
  src/main/webapp/resources/js/page/cash-exchange.js
  src/main/webapp/resources/js/page/employee-close.js
  src/main/webapp/resources/js/page/trade-cash.js
Labels: ✨ Feature

#341 고객 수정 기능 구현
  src/main/java/com/kcc/banking/domain/customer/controller/CustomerController.java
  src/main/java/com/kcc/banking/domain/customer/controller/CustomerRestController.java
  src/main/java/com/kcc/banking/domain/customer/dto/request/CustomerUpdate.java
  src/main/java/com/kcc/banking/domain/customer/dto/response/CustomerDetail.java
  src/main/java/com/kcc/banking/domain/customer/dto/response/UpdatedCustomer.java
  src/main/java/com/kcc/banking/domain/customer/mapper/CustomerMapper.java
  src/main/java/com/kcc/banking/domain/customer/service/CustomerService.java
  src/main/resources/mapper/customerMapper.xml
  src/main/webapp/WEB-INF/views/customer/customer-update.jsp
  src/main/webapp/WEB-INF/views/customer/employee-update.jsp
  src/main/webapp/resources/components/modal/search-modal-customer.jsp
  src/main/webapp/resources/css/page/customer-update.css
  src/main/webapp/resources/js/header.js
  src/main/webapp/resources/js/modal/customer-detail-modal.js
  src/main/webapp/resources/js/modal/search-customer-modal.js
  src/main/webapp/resources/js/page/customer-list.js
  src/main/webapp/resources/js/page/customer-save.js
  src/main/webapp/resources/js/page/customer-update.js
Labels: ✨ Feature

#347 OTP 발급/재발급 기능 구현
  src/main/java/com/kcc/banking/common/otp/OtpController.java
  src/main/java/com/kcc/banking/common/otp/OtpRestController.java
  src/main/java/com/kcc/banking/domain/customer/mapper/CustomerMapper.java
  src/main/java/com/kcc/banking/domain/customer/service/CustomerService.java
  src/main/resources/mapper/customerMapper.xml
  src/main/resources/schema.sql
  src/main/webapp/resources/components/modal/otp-detail-modal.jsp
  src/main/webapp/resources/js/page/otp-register.js
Labels: ✨ Feature

#349 OTP인증 구현
  src/main/java/com/kcc/banking/common/exception/ErrorCode.java
  src/main/java/com/kcc/banking/common/otp/OtpAuthentication.java
  src/main/java/com/kcc/banking/common/otp/OtpRestController.java
  src/main/java/com/kcc/banking/domain/account/dto/response/AccountOpenResultOfModal.java
  src/main/java/com/kcc/banking/domain/customer/dto/response/CustomerDetail.java
  src/main/resources/mapper/accountMapper.xml
  src/main/webapp/WEB-INF/views/trade/account-transfer.jsp
  src/main/webapp/resources/components/modal/otp-input-modal.jsp
  src/main/webapp/resources/components/modal/search-modal-deposit-product.jsp
  src/main/webapp/resources/css/page/account-transfer.css
  src/main/webapp/resources/js/modal/account-search-modal.js
  src/main/webapp/resources/js/page/account-transfer.js
Labels: ✨ Feature

#353 매니저 마감 수정: 자유적금 단리/복리 이자 계산
  src/main/java/com/kcc/banking/domain/account/dto/response/AccountDetailForInterest.java
  src/main/java/com/kcc/banking/domain/business_day/service/BusinessDayManagementFacade.java
  src/main/java/com/kcc/banking/domain/interest/dto/request/SavingInterestCreate.java
  src/main/java/com/kcc/banking/domain/interest/mapper/InterestMapper.java
  src/main/java/com/kcc/banking/domain/interest/service/InterestService.java
  src/main/resources/data.sql
  src/main/resources/mapper/accountMapper.xml
  src/main/resources/mapper/interestMapper.xml
  src/main/resources/schema.sql
  src/main/webapp/resources/js/page/account-close.js
Labels: ✨ Feature

#355 대량이체 기능 마무리(1)
  src/main/java/com/kcc/banking/domain/bulk_transfer/controller/BulkTransferRestController.java
  src/main/resources/bulk-transfer-upload.xlsx
  src/main/webapp/WEB-INF/views/trade/bulk-transfer.jsp
  src/main/webapp/resources/css/page/bulk-transfer.css
  src/main/webapp/resources/js/page/bulk-transfer.js
Labels: ✨ Feature, ♻️ Refactor

#357 대량이체 실행 페이지 UI 마무리(2)
  src/main/webapp/WEB-INF/views/trade/bulk-transfer.jsp
  src/main/webapp/resources/components/modal/transfer-account-search-modal.jsp
  src/main/webapp/resources/css/page/bulk-transfer.css
  src/main/webapp/resources/js/modal/account-search-modal.js
  src/main/webapp/resources/js/page/account-transfer.js
  src/main/webapp/resources/js/page/bulk-transfer.js
  src/main/webapp/resources/js/page/trade-cash.js
Labels: 🐛 BugFix, ✨ Feature, ♻️ Refactor

#359 대량이체 입금계좌 정보 수정 기능 추가
  src/main/webapp/WEB-INF/views/trade/bulk-transfer.jsp
  src/main/webapp/resources/css/page/bulk-transfer.css
  src/main/webapp/resources/css/styles.css
  src/main/webapp/resources/js/page/bulk-transfer.js
Labels: ✨ Feature

#361 대량 이체 재전송 기능 구현
  src/main/java/com/kcc/banking/domain/bulk_transfer/controller/BulkTransferRestController.java
  src/main/java/com/kcc/banking/domain/trade/controller/TradeRestController.java
  src/main/java/com/kcc/banking/domain/trade/dto/response/TradeDetail.java
  src/main/java/com/kcc/banking/domain/trade/mapper/TradeMapper.java
  src/main/java/com/kcc/banking/domain/trade/service/AccountTradeFacade.java
  src/main/java/com/kcc/banking/domain/trade/service/TradeService.java
  src/main/resources/mapper/tradeMapper.xml
  src/main/webapp/resources/js/page/bulk-transfer-result.js
  src/main/webapp/resources/js/page/bulk-transfer.js
Labels: ✨ Feature

#363 자유적금 해지 분기처리 추가
  src/main/java/com/kcc/banking/domain/account/controller/AccountRestController.java
  src/main/java/com/kcc/banking/domain/account/dto/response/AccountOfModal.java
  src/main/java/com/kcc/banking/domain/interest/controller/InterestRestController.java
  src/main/java/com/kcc/banking/domain/interest/dto/request/InterestCreate.java
  src/main/java/com/kcc/banking/domain/interest/dto/request/SavingInterestCreate.java
  src/main/java/com/kcc/banking/domain/interest/dto/response/InterestDetails.java
  src/main/java/com/kcc/banking/domain/interest/mapper/InterestMapper.java
  src/main/java/com/kcc/banking/domain/interest/service/InterestService.java
  src/main/java/com/kcc/banking/domain/trade/service/AccountTradeFacade.java
  src/main/resources/mapper/accountMapper.xml
  src/main/resources/mapper/interestMapper.xml
  src/main/resources/schema.sql
  src/main/webapp/WEB-INF/views/account/account-close-cancel.jsp
  src/main/webapp/WEB-INF/views/account/account-close.jsp
  src/main/webapp/WEB-INF/views/account/account-open.jsp
  src/main/webapp/WEB-INF/views/account/account-update.jsp
  src/main/webapp/WEB-INF/views/account/savings-account-close.jsp
  src/main/webapp/WEB-INF/views/account/savings-account-open.jsp
  src/main/webapp/WEB-INF/views/business-day/business-day-management.jsp
  src/main/webapp/WEB-INF/views/business-day/employee-close.jsp
  src/main/webapp/WEB-INF/views/business-day/manager-close.jsp
  src/main/webapp/WEB-INF/views/cash-exchange/cash-exchange-close.jsp
  src/main/webapp/WEB-INF/views/cash-exchange/cash-exchange.jsp
  src/main/webapp/WEB-INF/views/customer/customer-list.jsp
  src/main/webapp/WEB-INF/views/customer/customer-save.jsp
  src/main/webapp/WEB-INF/views/customer/customer-update.jsp
  src/main/webapp/WEB-INF/views/customer/otp-register.jsp
  src/main/webapp/WEB-INF/views/dashboard/employee-dashboard.jsp
  src/main/webapp/WEB-INF/views/dashboard/manager-dashboard.jsp
  src/main/webapp/WEB-INF/views/employee/employee-list.jsp
  src/main/webapp/WEB-INF/views/employee/employee-save.jsp
  src/main/webapp/WEB-INF/views/employee/employee-update.jsp
  src/main/webapp/WEB-INF/views/trade/account-transfer-cancel.jsp
  src/main/webapp/WEB-INF/views/trade/account-transfer.jsp
  src/main/webapp/WEB-INF/views/trade/bulk-transfer-result.jsp
  src/main/webapp/WEB-INF/views/trade/bulk-transfer.jsp
  src/main/webapp/WEB-INF/views/trade/cash-trade.jsp
  src/main/webapp/WEB-INF/views/trade/trade-list.jsp
  src/main/webapp/resources/css/page/account-transfer.css
  src/main/webapp/resources/css/page/bulk-transfer.css
  src/main/webapp/resources/css/page/trade-cash.css
  src/main/webapp/resources/css/styles.css
  src/main/webapp/resources/js/modal/business-day-update-modal.js
  src/main/webapp/resources/js/page/account-close.js
  src/main/webapp/resources/js/page/savings-account-close.js
Labels: ✨ Feature

#366 정기적금 해지 계좌 불러오기 API
  src/main/java/com/kcc/banking/domain/account/controller/AccountRestController.java
  src/main/java/com/kcc/banking/domain/account/dto/response/CloseSavingsAccountTotal.java
  src/main/java/com/kcc/banking/domain/account/mapper/AccountMapper.java
  src/main/java/com/kcc/banking/domain/account/service/AccountService.java
  src/main/resources/mapper/accountMapper.xml
  src/main/resources/schema.sql
  src/main/webapp/WEB-INF/views/account/savings-account-close.jsp
  src/main/webapp/resources/js/modal/search-customer-modal.js
  src/main/webapp/resources/js/page/savings-account-close.js
Labels: ✨ Feature

#368 담당자 현금잔액 API연동
  src/main/java/com/kcc/banking/domain/business_day_close/controller/BusinessDayCloseRestController.java
  src/main/java/com/kcc/banking/domain/business_day_close/service/BusinessDayCloseService.java
  src/main/webapp/resources/css/page/trade-cash.css
  src/main/webapp/resources/js/page/trade-cash.js
Labels: ✨ Feature

#369 중도해지 테이블 통합
  src/main/java/com/kcc/banking/domain/account/controller/AccountRestController.java
  src/main/java/com/kcc/banking/domain/account/dto/response/AccountOfModal.java
  src/main/java/com/kcc/banking/domain/account/dto/response/CloseSavingsFlexibleAccountTotal.java
  src/main/webapp/WEB-INF/views/account/savings-account-close.jsp
  src/main/webapp/resources/js/page/savings-account-close.js
Labels: ✨ Feature

#371 적금 해지 이율 계산 구현
  src/main/java/com/kcc/banking/domain/account/controller/AccountRestController.java
  src/main/java/com/kcc/banking/domain/account/dto/response/CloseSavingsFlexibleAccountTotal.java
  src/main/java/com/kcc/banking/domain/account/mapper/AccountMapper.java
  src/main/java/com/kcc/banking/domain/account/service/AccountService.java
  src/main/resources/mapper/accountMapper.xml
  src/main/webapp/WEB-INF/views/account/savings-account-close.jsp
  src/main/webapp/resources/js/header.js
  src/main/webapp/resources/js/page/savings-account-close.js
Labels: ✨ Feature
