Repository NeoJumper/MicroBankingSystem, pull requests merged in 2024-11, with the labels that each got.

#373 정기적금 해지 이율 계산
  src/main/java/com/kcc/banking/domain/account/dto/response/CloseSavingsAccountTotal.java
  src/main/webapp/resources/js/page/savings-account-close.js
Labels: ✨ Feature

#376 예약이체 기본 틀 작성
  src/main/java/com/kcc/banking/domain/reserve_transfer/controller/ReserveTransferController.java
  src/main/java/com/kcc/banking/domain/reserve_transfer/controller/ReserveTransferRestController.java
  src/main/java/com/kcc/banking/domain/reserve_transfer/dto/request/ReserveTransferCreate.java
  src/main/java/com/kcc/banking/domain/reserve_transfer/mapper/ReserveTransferMapper.java
  src/main/java/com/kcc/banking/domain/reserve_transfer/service/ReserveTransferService.java
  src/main/java/com/kcc/banking/domain/trade/dto/request/TransferTradeCreate.java
  src/main/java/com/kcc/banking/domain/trade/service/AccountTradeFacade.java
  src/main/resources/mapper/reserveTransferMapper.xml
  src/main/resources/schema.sql
  src/main/webapp/WEB-INF/views/trade/reserve-list.jsp
  src/main/webapp/resources/js/sidebar.js
Labels: ✨ Feature

#377 자유 적금 단리/복리 이자 테스트
  src/main/java/com/kcc/banking/domain/business_day/service/BusinessDayManagementFacade.java
  src/main/java/com/kcc/banking/domain/business_day_close/controller/BusinessDayCloseRestController.java
  src/main/java/com/kcc/banking/domain/interest/dto/request/SavingInterestCreate.java
  src/main/java/com/kcc/banking/domain/interest/service/InterestService.java
  src/main/resources/schema.sql
  src/main/webapp/resources/js/page/savings-account-close.js
  src/test/java/com/kcc/banking/domain/interest/controller/InterestCalculationTest.java
  src/test/resources/test-data.sql
  src/test/resources/test-schema.sql
Labels: ✅ Test

#379 이체한도 조회/변경 기능 구현
  src/main/java/com/kcc/banking/domain/account/controller/AccountController.java
  src/main/java/com/kcc/banking/domain/account/controller/AccountRestController.java
  src/main/java/com/kcc/banking/domain/account/dto/request/AccountUpdate.java
  src/main/java/com/kcc/banking/domain/account/dto/response/AccountOpenResultOfModal.java
  src/main/java/com/kcc/banking/domain/account/service/AccountService.java
  src/main/resources/mapper/accountMapper.xml
  src/main/webapp/WEB-INF/views/account/transfer-limit-update.jsp
  src/main/webapp/WEB-INF/views/customer/otp-register.jsp
  src/main/webapp/resources/css/page/transfer-limit-update.css
  src/main/webapp/resources/js/modal/account-search-modal.js
  src/main/webapp/resources/js/page/transfer-limit-update.js
  src/main/webapp/resources/js/sidebar.js
Labels: ✨ Feature

#381 예약이체 등록 기능 구현
  src/main/java/com/kcc/banking/domain/reserve_transfer/service/ReserveTransferService.java
  src/main/resources/mapper/accountMapper.xml
  src/main/resources/mapper/reserveTransferMapper.xml
  src/main/webapp/WEB-INF/views/trade/account-transfer.jsp
  src/main/webapp/resources/js/page/account-transfer.js
Labels: ✨ Feature

#383 대량이체 CSS수정
  src/main/webapp/WEB-INF/views/trade/bulk-transfer.jsp
  src/main/webapp/resources/css/page/bulk-transfer.css
  src/main/webapp/resources/js/page/bulk-transfer.js
Labels: ♻️ Refactor

#385 대량이체 기능 마무리
  src/main/java/com/kcc/banking/common/config/AsyncConfig.java
  src/main/java/com/kcc/banking/common/util/TransactionFunction.java
  src/main/java/com/kcc/banking/common/util/TransactionService.java
  src/main/java/com/kcc/banking/domain/bulk_transfer/controller/BulkTransferRestController.java
  src/main/java/com/kcc/banking/domain/bulk_transfer/dto/request/BulkTransferCreate.java
  src/main/java/com/kcc/banking/domain/bulk_transfer/dto/request/BulkTransferUpdate.java
  src/main/java/com/kcc/banking/domain/bulk_transfer/dto/response/BulkTransferProgressStatus.java
  src/main/java/com/kcc/banking/domain/bulk_transfer/dto/response/TransferProgress.java
  src/main/java/com/kcc/banking/domain/bulk_transfer/mapper/BulkTransferMapper.java
  src/main/java/com/kcc/banking/domain/bulk_transfer/service/BulkTransferService.java
  src/main/java/com/kcc/banking/domain/trade/service/AccountTradeFacade.java
  src/main/resources/mapper/accountMapper.xml
  src/main/resources/mapper/bulkTransferMapper.xml
  src/main/resources/schema.sql
  src/main/webapp/WEB-INF/views/trade/bulk-transfer-result.jsp
  src/main/webapp/WEB-INF/views/trade/bulk-transfer.jsp
  src/main/webapp/resources/css/page/bulk-transfer.css
  src/main/webapp/resources/js/page/bulk-transfer-result.js
  src/main/webapp/resources/js/page/bulk-transfer.js
  src/test/java/com/kcc/banking/MicroBankingSystemApplicationTests.java
Labels: ✨ Feature

#387 자유적금 해지 계좌 정보 테이블 추가
  src/main/java/com/kcc/banking/domain/interest/service/InterestService.java
  src/main/webapp/WEB-INF/views/account/savings-account-close.jsp
  src/main/webapp/resources/js/page/savings-account-close.js
Labels: ✨ Feature

#389 대량이체 기능 마무리(2)
  src/main/java/com/kcc/banking/domain/bulk_transfer/dto/request/BulkTransferCreate.java
  src/main/java/com/kcc/banking/domain/bulk_transfer/dto/response/BulkTransferDetail.java
  src/main/java/com/kcc/banking/domain/trade/service/AccountTradeFacade.java
  src/main/resources/mapper/bulkTransferMapper.xml
  src/main/resources/schema.sql
  src/main/webapp/WEB-INF/views/trade/bulk-transfer-result.jsp
  src/main/webapp/WEB-INF/views/trade/bulk-transfer.jsp
  src/main/webapp/WEB-INF/views/trade/trade-list.jsp
  src/main/webapp/resources/components/modal/employee-search-modal.jsp
  src/main/webapp/resources/components/modal/search-modal-customer.jsp
  src/main/webapp/resources/css/modal/account-search-modal.css
  src/main/webapp/resources/css/modal/businessday-update-modal.css
  src/main/webapp/resources/css/modal/search-modal-customer.css
  src/main/webapp/resources/css/page/bulk-transfer.css
  src/main/webapp/resources/js/page/bulk-transfer-result.js
  src/main/webapp/resources/js/page/bulk-transfer.js
  src/main/webapp/resources/js/page/customer-update.js
  src/main/webapp/resources/js/page/employee-update.js
  src/main/webapp/resources/js/page/trade-list.js
Labels: ✨ Feature, ♻️ Refactor

#405 행원 관리 리팩토링
  src/main/java/com/kcc/banking/domain/customer/dto/request/CustomerSearch.java
  src/main/java/com/kcc/banking/domain/customer/service/CustomerService.java
  src/main/java/com/kcc/banking/domain/employee/controller/EmployeeController.java
  src/main/java/com/kcc/banking/domain/employee/controller/EmployeeRestController.java
  src/main/java/com/kcc/banking/domain/employee/dto/request/EmployeeCreate.java
  src/main/java/com/kcc/banking/domain/employee/dto/request/EmployeeSearch.java
  src/main/java/com/kcc/banking/domain/employee/dto/request/EmployeeUpdate.java
  src/main/java/com/kcc/banking/domain/employee/dto/response/EmployeeDetail.java
  src/main/java/com/kcc/banking/domain/employee/dto/response/EmployeeSearchInfo.java
  src/main/java/com/kcc/banking/domain/employee/dto/response/EmployeeSearchResult.java
  src/main/java/com/kcc/banking/domain/employee/mapper/EmployeeMapper.java
  src/main/java/com/kcc/banking/domain/employee/service/EmployeeService.java
  src/main/resources/mapper/customerMapper.xml
  src/main/resources/mapper/employeeMapper.xml
  src/main/resources/schema.sql
  src/main/webapp/WEB-INF/views/employee/employee-list.jsp
  src/main/webapp/WEB-INF/views/employee/employee-save.jsp
  src/main/webapp/WEB-INF/views/employee/employee-update.jsp
  src/main/webapp/resources/components/modal/employee-detail-modal.jsp
  src/main/webapp/resources/css/modal/employee-detail-modal.css
  src/main/webapp/resources/css/page/employee-save.css
  src/main/webapp/resources/css/page/employee-update.css
  src/main/webapp/resources/js/modal/employee-detail-modal.js
  src/main/webapp/resources/js/page/customer-save.js
  src/main/webapp/resources/js/page/employee-list.js
  src/main/webapp/resources/js/page/employee-save.js
  src/main/webapp/resources/js/page/employee-update.js
Labels: ✨ Feature, ♻️ Refactor

#408 자유적금 해지 요청 API 추가
  src/main/java/com/kcc/banking/common/exception/ErrorCode.java
  src/main/java/com/kcc/banking/domain/account/controller/AccountRestController.java
  src/main/java/com/kcc/banking/domain/account/dto/request/AccountClose.java
  src/main/java/com/kcc/banking/domain/account/dto/request/StatusWithTrade.java
  src/main/java/com/kcc/banking/domain/account/dto/response/AccountCloseResult.java
  src/main/java/com/kcc/banking/domain/account/dto/response/CloseSavingsAccount.java
  src/main/java/com/kcc/banking/domain/account/dto/response/CloseSavingsAccountTotal.java
  src/main/java/com/kcc/banking/domain/account/dto/response/CloseSavingsFlexibleAccountTotal.java
  src/main/java/com/kcc/banking/domain/account/service/AccountCloseFacade.java
  src/main/java/com/kcc/banking/domain/account/service/AccountService.java
  src/main/java/com/kcc/banking/domain/business_day/service/BusinessDayManagementFacade.java
  src/main/java/com/kcc/banking/domain/interest/dto/request/SavingInterestCreate.java
  src/main/java/com/kcc/banking/domain/interest/dto/response/InterestDetails.java
  src/main/java/com/kcc/banking/domain/interest/service/InterestService.java
  src/main/java/com/kcc/banking/domain/trade/controller/TradeRestController.java
  src/main/java/com/kcc/banking/domain/trade/dto/request/CloseAccount.java
  src/main/java/com/kcc/banking/domain/trade/service/AccountTradeFacade.java
  src/main/java/com/kcc/banking/domain/trade/service/TradeService.java
  src/main/resources/mapper/accountMapper.xml
  src/main/webapp/WEB-INF/views/account/savings-account-close.jsp
  src/main/webapp/resources/js/page/account-close-cancel.js
  src/main/webapp/resources/js/page/savings-account-close.js
Labels: ✨ Feature

#409 금입 입력란 한글 금액 표기
  src/main/resources/mapper/customerMapper.xml
  src/main/webapp/WEB-INF/views/account/account-open.jsp
  src/main/webapp/WEB-INF/views/trade/account-transfer.jsp
  src/main/webapp/WEB-INF/views/trade/cash-trade.jsp
  src/main/webapp/resources/css/page/account-open.css
  src/main/webapp/resources/css/page/account-transfer.css
  src/main/webapp/resources/css/page/trade-cash.css
  src/main/webapp/resources/js/footer.js
  src/main/webapp/resources/js/page/account-open.js
  src/main/webapp/resources/js/page/account-transfer.js
  src/main/webapp/resources/js/page/bulk-transfer.js
  src/main/webapp/resources/js/page/trade-cash.js
Labels: ✨ Feature

#411 Feature/#392 savings account valid
  src/main/webapp/WEB-INF/views/account/account-open.jsp
  src/main/webapp/WEB-INF/views/account/savings-account-open.jsp
  src/main/webapp/resources/components/modal/search-modal-product.jsp
  src/main/webapp/resources/css/modal/product-search-modal.css
  src/main/webapp/resources/css/page/savings-account-open.css
  src/main/webapp/resources/js/modal/product-search-modal.js
  src/main/webapp/resources/js/page/savings-account-open.js
Labels: 🐛 BugFix, ♻️ Refactor

#415 마감 DateTimeFormatter 수정
  src/main/java/com/kcc/banking/domain/interest/service/InterestService.java
Labels: 🐛 BugFix

#416 fix: delete <where>
  src/main/resources/mapper/employeeMapper.xml
Labels: 🐛 BugFix

#418 행원 조회 버그 수정
  src/main/resources/mapper/employeeMapper.xml
  src/main/webapp/resources/js/modal/employee-search-modal.js
Labels: 🐛 BugFix

#419 OTP UI 리팩토링
  src/main/webapp/resources/assets/authentication.png
  src/main/webapp/resources/assets/qr-code.png
  src/main/webapp/resources/components/modal/otp-detail-modal.jsp
  src/main/webapp/resources/css/modal/otp-detail-modal.css
  src/main/webapp/resources/css/styles.css
  src/main/webapp/resources/js/page/transfer-limit-update.js
Labels: ♻️ Refactor

#421 결과 모달 UI 수정
  src/main/java/com/kcc/banking/domain/trade/dto/response/TradeDetail.java
  src/main/java/com/kcc/banking/domain/trade/service/AccountTradeFacade.java
  src/main/java/com/kcc/banking/domain/trade/service/TradeService.java
  src/main/webapp/resources/assets/account-close.png
  src/main/webapp/resources/assets/account-open.png
  src/main/webapp/resources/assets/banker.png
  src/main/webapp/resources/assets/transfer-result.png
  src/main/webapp/resources/components/modal/account-close-result-modal.jsp
  src/main/webapp/resources/components/modal/result-modal-open-account.jsp
  src/main/webapp/resources/components/modal/trade-cash-result-modal.jsp
  src/main/webapp/resources/components/modal/transfer-result-modal.jsp
  src/main/webapp/resources/css/modal/account-close-result-modal.css
  src/main/webapp/resources/css/modal/cash-trade-result-modal.css
  src/main/webapp/resources/css/modal/result-modal-open-account.css
  src/main/webapp/resources/css/modal/transfer-result-modal.css
  src/main/webapp/resources/css/page/trade-cash.css
  src/main/webapp/resources/js/page/trade-cash.js
Labels: ♻️ Refactor

#422 자유적금 해지 - 세율 계산 추가
  src/main/java/com/kcc/banking/domain/account/dto/response/CloseSavingsFlexibleAccountTotal.java
  src/main/java/com/kcc/banking/domain/account/service/AccountCloseFacade.java
  src/main/resources/data.sql
  src/main/webapp/WEB-INF/views/account/account-close.jsp
  src/main/webapp/WEB-INF/views/account/savings-account-close.jsp
  src/main/webapp/resources/js/page/account-close.js
  src/main/webapp/resources/js/page/savings-account-close.js
Labels: ✨ Feature

#423 거래 취소는 출금과 해지에 대해서만 가능하도록 변경
  src/main/webapp/resources/components/modal/account-close-result-modal.jsp
  src/main/webapp/resources/js/footer.js
  src/main/webapp/resources/js/page/account-close-cancel.js
  src/main/webapp/resources/js/page/bulk-transfer.js
  src/main/webapp/resources/js/page/trade-list.js
Labels: ♻️ Refactor

#424 거래 취소 UI 수정
  src/main/webapp/WEB-INF/views/trade/account-transfer-cancel.jsp
Labels: ♻️ Refactor

#429 이자내역 테스트 코드
  src/main/java/com/kcc/banking/domain/business_day/service/BusinessDayManagementFacade.java
  src/main/java/com/kcc/banking/domain/business_day_close/controller/BusinessDayCloseRestController.java
  src/main/java/com/kcc/banking/domain/interest/dto/request/SavingInterestCreate.java
  src/main/java/com/kcc/banking/domain/interest/service/InterestService.java
  src/test/java/com/kcc/banking/domain/interest/controller/InterestCalculationTest.java
Labels: ✨ Feature

#431 검색 모달 UI및 검색 요청 버그 수정
  src/main/webapp/WEB-INF/views/account/savings-account-open.jsp
  src/main/webapp/WEB-INF/views/customer/customer-list.jsp
  src/main/webapp/WEB-INF/views/employee/employee-list.jsp
  src/main/webapp/resources/components/modal/account-search-modal.jsp
  src/main/webapp/resources/components/modal/employee-detail-modal.jsp
  src/main/webapp/resources/components/modal/employee-search-modal.jsp
  src/main/webapp/resources/components/modal/search-modal-customer.jsp
  src/main/webapp/resources/css/modal/account-search-modal.css
  src/main/webapp/resources/css/modal/employee-detail-modal.css
  src/main/webapp/resources/css/modal/employee-search-modal.css
  src/main/webapp/resources/css/modal/product-search-modal.css
  src/main/webapp/resources/css/modal/search-modal-customer.css
  src/main/webapp/resources/js/modal/account-search-modal.js
  src/main/webapp/resources/js/modal/business-day-update-modal.js
  src/main/webapp/resources/js/modal/employee-search-modal.js
  src/main/webapp/resources/js/modal/search-customer-modal.js
  src/main/webapp/resources/js/page/employee-list.js
Labels: 🐛 BugFix, ♻️ Refactor

#433 대량이체 OTP적용
  src/main/java/com/kcc/banking/domain/bulk_transfer/dto/response/BulkTransferDetail.java
  src/main/java/com/kcc/banking/domain/bulk_transfer/service/BulkTransferService.java
  src/main/webapp/WEB-INF/views/trade/bulk-transfer-result.jsp
  src/main/webapp/WEB-INF/views/trade/bulk-transfer.jsp
  src/main/webapp/resources/css/page/bulk-transfer.css
  src/main/webapp/resources/js/page/account-transfer.js
  src/main/webapp/resources/js/page/bulk-transfer-result.js
  src/main/webapp/resources/js/page/bulk-transfer.js
Labels: ✨ Feature, ♻️ Refactor

#437 시현 전 병합
  src/main/webapp/WEB-INF/views/trade/bulk-transfer.jsp
  src/main/webapp/resources/js/page/bulk-transfer-result.js
Labels: ✅ Test

#442 중도 해지시 단리로 이자 계산
  src/main/java/com/kcc/banking/domain/account/service/AccountCloseFacade.java
  src/main/webapp/resources/js/page/savings-account-close.js
  src/test/java/com/kcc/banking/domain/account/service/AccountCloseFacadeTest.java
  src/test/java/com/kcc/banking/domain/interest/controller/InterestCalculationTest.java
  src/test/resources/test-data.sql
Labels: ✨ Feature

#444 만기 후 이자 재계산 완료
  src/main/java/com/kcc/banking/domain/account/dto/response/AccountDetailForInterest.java
  src/main/java/com/kcc/banking/domain/interest/dto/request/SavingInterestCreate.java
  src/main/java/com/kcc/banking/domain/interest/service/InterestService.java
  src/main/resources/mapper/accountMapper.xml
  src/main/webapp/resources/js/page/savings-account-close.js
  src/test/java/com/kcc/banking/domain/interest/controller/InterestCalculationTest.java
  src/test/java/com/kcc/banking/domain/interest/service/InterestServiceTest.java
  src/test/resources/test-schema.sql
Labels: ✨ Feature

#447 대량이체 이체정보 목록 CSS수정
  src/main/webapp/resources/css/page/bulk-transfer.css
  src/main/webapp/resources/js/page/bulk-transfer-result.js
  src/main/webapp/resources/js/page/bulk-transfer.js
Labels: ♻️ Refactor

#449 스크립트 수정
  .github/workflows/work.yml
Labels: 🐛 BugFix

#450 패키징 변경(jar -> war)
  Dockerfile
  pom.xml
  src/main/java/com/kcc/banking/MicroBankingSystemApplication.java
Labels: 🐛 BugFix, 🚀deploy

#451 Dockerhub경로 재설정
  .github/workflows/work.yml
Labels: 🐛 BugFix, 🚀deploy

#452 배포 테스트
  src/main/java/com/kcc/banking/MicroBankingSystemApplication.java
Labels: 🚀deploy, ✅ Test

#453 yml수정
  .github/workflows/work.yml
  src/main/java/com/kcc/banking/MicroBankingSystemApplication.java
Labels: 🚀deploy

#455 날짜 포맷 수정
  src/main/resources/data.sql
Labels: 🐛 BugFix, 🚀deploy

#456 SQL버그 수정
  src/main/resources/data.sql
Labels: 🐛 BugFix, 🚀deploy

#457 날짜 포맷 수정
  src/main/resources/data.sql
Labels: 🐛 BugFix, 🚀deploy

#459 대시보드 다운로드 기능 추가
  src/main/webapp/WEB-INF/views/dashboard/manager-dashboard.jsp
  src/main/webapp/resources/js/page/manager-dashboard.js
Labels: ✨ Feature

#460 자동이체 sql 수정
  src/main/resources/data.sql
  src/main/webapp/WEB-INF/views/dashboard/manager-dashboard.jsp
  src/main/webapp/resources/js/page/manager-dashboard.js
Labels: 🚀deploy

#461 자동이체 SQL수정
  src/main/resources/data.sql
Labels: 🐛 BugFix, 🚀deploy

#462 init구문 수정
  src/main/java/com/kcc/banking/common/init/InitData.java
Labels: 🐛 BugFix, 🚀deploy

#463 prefix변경 테스트
  pom.xml
  src/main/java/com/kcc/banking/domain/employee/controller/EmployeeController.java
Labels: 🚀deploy, ✅ Test

#464 tomcat의존성 추가
  pom.xml
Labels: 🚀deploy, 🛠 Setting

#465 view 경로변경
  src/main/java/com/kcc/banking/domain/employee/controller/EmployeeController.java
Labels: 🚀deploy

#466 수정사항 반영
  pom.xml
  src/main/java/com/kcc/banking/MicroBankingSystemApplication.java
  src/main/java/com/kcc/banking/domain/employee/controller/EmployeeController.java
Labels: 🚀deploy

#467 수정
  src/main/java/com/kcc/banking/domain/employee/controller/EmployeeController.java
Labels: 🚀deploy

#468 수정
  pom.xml
Labels: 🚀deploy

#469 방화벽 추가
  src/main/java/com/kcc/banking/common/auth/SecurityConfig.java
  src/main/java/com/kcc/banking/domain/employee/controller/EmployeeController.java
Labels: 🚀deploy

#470 로깅 추가
  src/main/java/com/kcc/banking/domain/employee/controller/EmployeeController.java
Labels: 🚀deploy

#475 MAIN DEPLOY
  src/main/java/com/kcc/banking/common/init/InitData.java
  src/main/java/com/kcc/banking/domain/account/dto/response/CloseSavingsFlexibleAccountTotal.java
  src/main/java/com/kcc/banking/domain/account/service/AccountCloseFacade.java
  src/main/java/com/kcc/banking/domain/dashboard/controller/DashboardRestController.java
  src/main/java/com/kcc/banking/domain/dashboard/dto/response/DailyEmployeeTransactionVolumeChart.java
  src/main/java/com/kcc/banking/domain/dashboard/dto/response/MonthlyTradeTypeChart.java
  src/main/java/com/kcc/banking/domain/dashboard/dto/response/TransactionTypeCount.java
  src/main/java/com/kcc/banking/domain/dashboard/mapper/DashboardMapper.java
  src/main/java/com/kcc/banking/domain/dashboard/service/DashboardService.java
  src/main/resources/data.sql
  src/main/resources/mapper/dashboardMapper.xml
  src/main/webapp/WEB-INF/views/account/savings-account-close.jsp
  src/main/webapp/WEB-INF/views/dashboard/employee-dashboard.jsp
  src/main/webapp/WEB-INF/views/dashboard/manager-dashboard.jsp
  src/main/webapp/resources/css/page/manager-dashboard.css
  src/main/webapp/resources/js/footer.js
  src/main/webapp/resources/js/page/account-close.js
  src/main/webapp/resources/js/page/employee-dashboard.js
  src/main/webapp/resources/js/page/manager-dashboard.js
  src/main/webapp/resources/js/page/savings-account-close.js
Labels: 🚀deploy

#478 날짜 데이터 타입 수정
  src/main/java/com/kcc/banking/domain/account/dto/request/AccountCreate.java
  src/main/java/com/kcc/banking/domain/account/dto/request/AccountUpdate.java
  src/main/java/com/kcc/banking/domain/account/service/AccountCloseFacade.java
  src/main/java/com/kcc/banking/domain/bulk_transfer/dto/request/BulkTransferCreate.java
  src/main/java/com/kcc/banking/domain/business_day/dto/request/BusinessDayUpdate.java
  src/main/java/com/kcc/banking/domain/business_day/dto/response/BusinessDay.java
  src/main/java/com/kcc/banking/domain/business_day/service/BusinessDayManagementFacade.java
  src/main/java/com/kcc/banking/domain/business_day/service/BusinessDayService.java
  src/main/java/com/kcc/banking/domain/business_day_close/dto/request/BranchClosingUpdate.java
  src/main/java/com/kcc/banking/domain/business_day_close/dto/request/EmployeeAdditionalUpdate.java
  src/main/java/com/kcc/banking/domain/business_day_close/dto/request/EmployeeClosingUpdate.java
  src/main/java/com/kcc/banking/domain/business_day_close/service/BusinessDayCloseService.java
  src/main/java/com/kcc/banking/domain/cash_exchange/dto/request/CashExchangeCreate.java
  src/main/java/com/kcc/banking/domain/common/dto/request/CurrentData.java
  src/main/java/com/kcc/banking/domain/common/service/CommonService.java
  src/main/java/com/kcc/banking/domain/customer/dto/request/CustomerCreate.java
  src/main/java/com/kcc/banking/domain/customer/dto/request/CustomerUpdate.java
  src/main/java/com/kcc/banking/domain/customer/dto/response/CreatedCustomer.java
  src/main/java/com/kcc/banking/domain/customer/dto/response/UpdatedCustomer.java
  src/main/java/com/kcc/banking/domain/dashboard/service/DashboardService.java
  src/main/java/com/kcc/banking/domain/employee/dto/request/BusinessDateAndBranchId.java
  src/main/java/com/kcc/banking/domain/employee/dto/request/EmployeeCreate.java
  src/main/java/com/kcc/banking/domain/employee/dto/response/CreatedEmployee.java
  src/main/java/com/kcc/banking/domain/employee/dto/response/EmployeeDetail.java
  src/main/java/com/kcc/banking/domain/employee/service/EmployeeService.java
  src/main/java/com/kcc/banking/domain/interest/dto/request/InterestCreate.java
  src/main/java/com/kcc/banking/domain/interest/dto/request/PaymentStatusUpdate.java
  src/main/java/com/kcc/banking/domain/interest/dto/request/PaymentUpdate.java
  src/main/java/com/kcc/banking/domain/interest/dto/request/SavingInterestCreate.java
  src/main/java/com/kcc/banking/domain/interest/dto/response/InterestDetails.java
  src/main/java/com/kcc/banking/domain/interest/service/InterestService.java
  src/main/java/com/kcc/banking/domain/trade/controller/TradeController.java
  src/main/java/com/kcc/banking/domain/trade/dto/request/TradeCreate.java
  src/main/java/com/kcc/banking/domain/trade/dto/request/TradeSearch.java
  src/main/java/com/kcc/banking/domain/trade/dto/response/TradeDetail.java
  src/main/java/com/kcc/banking/domain/trade/service/AccountTradeFacade.java
  src/main/java/com/kcc/banking/domain/trade/service/TradeService.java
  src/test/java/com/kcc/banking/MicroBankingSystemApplicationTests.java
  src/test/java/com/kcc/banking/domain/interest/controller/InterestCalculationTest.java
  src/test/java/com/kcc/banking/domain/interest/service/InterestServiceTest.java
Labels: 🐛 BugFix

#480 MAIN MERGE
  src/main/java/com/kcc/banking/domain/account/dto/request/AccountCreate.java
  src/main/java/com/kcc/banking/domain/account/dto/request/AccountUpdate.java
  src/main/java/com/kcc/banking/domain/account/service/AccountCloseFacade.java
  src/main/java/com/kcc/banking/domain/bulk_transfer/dto/request/BulkTransferCreate.java
  src/main/java/com/kcc/banking/domain/business_day/dto/request/BusinessDayUpdate.java
  src/main/java/com/kcc/banking/domain/business_day/dto/response/BusinessDay.java
  src/main/java/com/kcc/banking/domain/business_day/service/BusinessDayManagementFacade.java
  src/main/java/com/kcc/banking/domain/business_day/service/BusinessDayService.java
  src/main/java/com/kcc/banking/domain/business_day_close/dto/request/BranchClosingUpdate.java
  src/main/java/com/kcc/banking/domain/business_day_close/dto/request/EmployeeAdditionalUpdate.java
  src/main/java/com/kcc/banking/domain/business_day_close/dto/request/EmployeeClosingUpdate.java
  src/main/java/com/kcc/banking/domain/business_day_close/service/BusinessDayCloseService.java
  src/main/java/com/kcc/banking/domain/cash_exchange/dto/request/CashExchangeCreate.java
  src/main/java/com/kcc/banking/domain/common/dto/request/CurrentData.java
  src/main/java/com/kcc/banking/domain/common/service/CommonService.java
  src/main/java/com/kcc/banking/domain/customer/dto/request/CustomerCreate.java
  src/main/java/com/kcc/banking/domain/customer/dto/request/CustomerUpdate.java
  src/main/java/com/kcc/banking/domain/customer/dto/response/CreatedCustomer.java
  src/main/java/com/kcc/banking/domain/customer/dto/response/UpdatedCustomer.java
  src/main/java/com/kcc/banking/domain/dashboard/service/DashboardService.java
  src/main/java/com/kcc/banking/domain/employee/dto/request/BusinessDateAndBranchId.java
  src/main/java/com/kcc/banking/domain/employee/dto/request/EmployeeCreate.java
  src/main/java/com/kcc/banking/domain/employee/dto/response/CreatedEmployee.java
  src/main/java/com/kcc/banking/domain/employee/dto/response/EmployeeDetail.java
  src/main/java/com/kcc/banking/domain/employee/service/EmployeeService.java
  src/main/java/com/kcc/banking/domain/interest/dto/request/InterestCreate.java
  src/main/java/com/kcc/banking/domain/interest/dto/request/PaymentStatusUpdate.java
  src/main/java/com/kcc/banking/domain/interest/dto/request/PaymentUpdate.java
  src/main/java/com/kcc/banking/domain/interest/dto/request/SavingInterestCreate.java
  src/main/java/com/kcc/banking/domain/interest/dto/response/InterestDetails.java
  src/main/java/com/kcc/banking/domain/interest/service/InterestService.java
  src/main/java/com/kcc/banking/domain/trade/controller/TradeController.java
  src/main/java/com/kcc/banking/domain/trade/dto/request/TradeCreate.java
  src/main/java/com/kcc/banking/domain/trade/dto/request/TradeSearch.java
  src/main/java/com/kcc/banking/domain/trade/dto/response/TradeDetail.java
  src/main/java/com/kcc/banking/domain/trade/service/AccountTradeFacade.java
  src/main/java/com/kcc/banking/domain/trade/service/TradeService.java
  src/test/java/com/kcc/banking/MicroBankingSystemApplicationTests.java
  src/test/java/com/kcc/banking/domain/interest/controller/InterestCalculationTest.java
  src/test/java/com/kcc/banking/domain/interest/service/InterestServiceTest.java
Labels: 🚀deploy

#481 타임존 설정
  src/main/java/com/kcc/banking/MicroBankingSystemApplication.java
  src/main/java/com/kcc/banking/common/init/InitData.java
  src/main/webapp/resources/js/page/business-day-management.js
  src/main/webapp/resources/js/page/customer-save.js
  src/main/webapp/resources/js/page/customer-update.js
Labels: 🚀deploy

#483 차트 크기 수정
  src/main/webapp/WEB-INF/views/business-day/manager-close.jsp
  src/main/webapp/resources/css/page/manager-dashboard.css
Labels: 🐛 BugFix

#485 헤더 & 인수도거래 수정
  src/main/java/com/kcc/banking/domain/business_day_close/dto/response/EmployeeClosingData.java
  src/main/webapp/WEB-INF/views/cash-exchange/cash-exchange-close.jsp
  src/main/webapp/WEB-INF/views/cash-exchange/cash-exchange.jsp
  src/main/webapp/resources/js/header.js
  src/main/webapp/resources/js/page/cash-exchange-close.js
  src/main/webapp/resources/js/sidebar.js
Labels: 🐛 BugFix

#487 잘못된 거래 삭제
  src/main/resources/data.sql
Labels: ✨ Feature

#488 잘못된 거래 삭제
  src/main/java/com/kcc/banking/domain/account/controller/AccountRestController.java
  src/main/java/com/kcc/banking/domain/bulk_transfer/controller/BulkTransferController.java
  src/main/java/com/kcc/banking/domain/business_day_close/dto/response/EmployeeClosingData.java
  src/main/java/com/kcc/banking/domain/trade/dto/request/TradeSearch.java
  src/main/java/com/kcc/banking/domain/trade/service/AccountTradeFacade.java
  src/main/resources/data.sql
  src/main/resources/mapper/accountMapper.xml
  src/main/resources/mapper/tradeMapper.xml
  src/main/webapp/WEB-INF/views/account/savings-account-close.jsp
  src/main/webapp/WEB-INF/views/account/savings-account-open.jsp
  src/main/webapp/WEB-INF/views/business-day/manager-close.jsp
  src/main/webapp/WEB-INF/views/cash-exchange/cash-exchange-close.jsp
  src/main/webapp/WEB-INF/views/cash-exchange/cash-exchange.jsp
  src/main/webapp/resources/css/page/manager-dashboard.css
  src/main/webapp/resources/js/header.js
  src/main/webapp/resources/js/page/bulk-transfer.js
  src/main/webapp/resources/js/page/cash-exchange-close.js
  src/main/webapp/resources/js/page/savings-account-close.js
  src/main/webapp/resources/js/page/savings-account-open.js
  src/main/webapp/resources/js/page/trade-cash.js
  src/main/webapp/resources/js/page/trade-list.js
  src/main/webapp/resources/js/sidebar.js
Labels: ✨ Feature

#492 더미데이터 수정 및 조건 수정, CSS 수정
  src/main/resources/data.sql
  src/main/resources/mapper/dashboardMapper.xml
  src/main/resources/mapper/tradeMapper.xml
  src/main/webapp/WEB-INF/views/business-day/employee-close.jsp
  src/main/webapp/WEB-INF/views/business-day/manager-close.jsp
Labels: ♻️ Refactor

#493 발표용 더미 데이터 수정
  src/main/java/com/kcc/banking/domain/account/dto/response/CloseSavingsAccountTotal.java
  src/main/java/com/kcc/banking/domain/account/service/AccountCloseFacade.java
  src/main/java/com/kcc/banking/domain/auto_transfer/controller/AutoTransferRestController.java
  src/main/java/com/kcc/banking/domain/auto_transfer/mapper/AutoTransferMapper.java
  src/main/java/com/kcc/banking/domain/auto_transfer/service/AutoTransferService.java
  src/main/java/com/kcc/banking/domain/reserve_transfer/dto/request/ReserveList.java
  src/main/java/com/kcc/banking/domain/trade/service/AccountTradeFacade.java
  src/main/resources/data.sql
  src/main/resources/mapper/autoTransferMapper.xml
  src/main/resources/mapper/dashboardMapper.xml
  src/main/resources/mapper/tradeMapper.xml
  src/main/webapp/WEB-INF/views/account/savings-account-close.jsp
  src/main/webapp/WEB-INF/views/business-day/employee-close.jsp
  src/main/webapp/WEB-INF/views/business-day/manager-close.jsp
  src/main/webapp/WEB-INF/views/trade/reserve-list.jsp
  src/main/webapp/resources/components/modal/result-modal-savings-open-account.jsp
  src/main/webapp/resources/js/modal/savings-account-open-result-modal.js
  src/main/webapp/resources/js/page/reserve-list.js
  src/main/webapp/resources/js/page/savings-account-close.js
  src/main/webapp/resources/js/page/savings-account-open.js
Labels: 🚀deploy, 🛠 Setting

#494 차트 & 리다이렉트 수정
  src/main/java/com/kcc/banking/common/init/InitData.java
  src/main/java/com/kcc/banking/common/sms/CoolSmsService.java
  src/main/java/com/kcc/banking/domain/dashboard/mapper/DashboardMapper.java
  src/main/java/com/kcc/banking/domain/dashboard/service/DashboardService.java
  src/main/resources/data.sql
  src/main/resources/mapper/dashboardMapper.xml
  src/main/webapp/WEB-INF/views/account/savings-account-open.jsp
  src/main/webapp/resources/js/page/employee-dashboard.js
  src/main/webapp/resources/js/page/savings-account-close.js
Labels: 🚀deploy

#496 적금 이름 변경
  src/main/resources/data.sql
Labels: 🚀deploy

#497 .
  src/main/java/com/kcc/banking/domain/business_day_close/dto/request/BranchClosingCreate.java
  src/main/java/com/kcc/banking/domain/business_day_close/dto/request/EmployeeClosingCreate.java
Labels: 🚀deploy

#498 ..
  src/main/java/com/kcc/banking/domain/business_day/dto/request/BusinessDayChange.java
  src/main/java/com/kcc/banking/domain/business_day_close/dto/request/BranchClosingCreate.java
  src/main/java/com/kcc/banking/domain/business_day_close/dto/request/EmployeeClosingCreate.java
  src/main/webapp/resources/js/modal/business-day-update-modal.js
Labels: 🚀deploy

#500 날짜검색 쿼리 수정
  src/main/resources/mapper/businessDayCloseMapper.xml
  src/main/resources/mapper/dashboardMapper.xml
Labels: 🚀deploy

#502 더미데이터 삭제 및 정기적금 해지 수정
  src/main/java/com/kcc/banking/common/init/InitData.java
  src/main/java/com/kcc/banking/domain/account/dto/response/CloseSavingsAccountTotal.java
  src/main/resources/data.sql
  src/main/webapp/resources/js/page/savings-account-close.js
Labels: 🐛 BugFix, ✨ Feature

#503 더미데이터 수정 및 정기적금 해지 수정
  src/main/java/com/kcc/banking/common/init/InitData.java
  src/main/java/com/kcc/banking/domain/account/dto/response/CloseSavingsAccountTotal.java
  src/main/resources/data.sql
  src/main/webapp/resources/js/page/savings-account-close.js
Labels: 🐛 BugFix, 🚀deploy

#506 더미 데이터 추가
  src/main/resources/data.sql
  src/main/resources/mapper/dashboardMapper.xml
  src/main/webapp/resources/js/page/employee-dashboard.js
Labels: ✨ Feature

#510 3번 행원 마감 & 마감 시 적금페이지 닫기
  src/main/resources/data.sql
  src/main/webapp/WEB-INF/views/account/savings-account-close.jsp
  src/main/webapp/WEB-INF/views/account/savings-account-open.jsp
  src/main/webapp/resources/js/page/savings-account-close.js
  src/main/webapp/resources/js/page/savings-account-open.js
Labels: ✨ Feature

#517 Fix/#515 width
  src/main/webapp/resources/js/page/manager-dashboard.js
Labels: 🐛 BugFix

#518 배포
  src/main/webapp/resources/js/page/manager-dashboard.js
Labels: 🚀deploy

#519 수정
  src/main/webapp/WEB-INF/views/trade/bulk-transfer-result.jsp
  src/main/webapp/resources/js/page/trade-list.js
Labels: 🚀deploy
