Repository NeoJumper/MicroBankingSystem, pull requests merged in 2024-09, with the labels that each got.

#3 헤더/메뉴바UI구현
  src/main/webapp/resources/components/header.jsp
  src/main/webapp/resources/components/sidebar.jsp
  src/main/webapp/resources/css/header.css
  src/main/webapp/resources/css/sidebar.css
  src/main/webapp/resources/css/styles.css
Labels: ✨ Feature

#6 공통 JS : footer 추가
  src/main/webapp/WEB-INF/views/index.jsp
  src/main/webapp/WEB-INF/views/transfer/account-transfer.jsp
  src/main/webapp/resources/assets/kcc-logo.png
  src/main/webapp/resources/js/footer.js
Labels: 🛠 Setting

#8 accountOpenUI
  pom.xml
  src/main/java/com/kcc/banking/HelloController.java
  src/main/webapp/WEB-INF/views/account/account-open.jsp
Labels: ✨ Feature

#10 공통 테이블 UI작업
  src/main/webapp/WEB-INF/views/account/account-open.jsp
  src/main/webapp/resources/css/commonTable.css
Labels: ✨ Feature

#12 행원 등록 UI구현
  src/main/java/com/kcc/banking/domain/employee/controller/EmployeeController.java
  src/main/webapp/WEB-INF/views/employee-save.jsp
  src/main/webapp/resources/components/sidebar.jsp
  src/main/webapp/resources/css/commonTable.css
  src/main/webapp/resources/css/styles.css
Labels: ✨ Feature

#14 고객 정보 검색 모달 UI 구현
  src/main/webapp/WEB-INF/views/account/account-open.jsp
Labels: ✨ Feature

#16 행원 추가 목록 표 수정
  src/main/webapp/WEB-INF/views/employee-save.jsp
  src/main/webapp/resources/css/commonTable.css
Labels: ♻️ Refactor

#20 헤더와 사이드바 수정
  src/main/java/com/kcc/banking/domain/transfer/controller/TransferController.java
  src/main/java/com/kcc/banking/domain/transfer/controller/TransferRestController.java
  src/main/webapp/WEB-INF/views/account/account-open.jsp
  src/main/webapp/WEB-INF/views/transfer/account-transfer.jsp
  src/main/webapp/resources/components/modal/account-search-modal.jsp
  src/main/webapp/resources/css/commonTable.css
  src/main/webapp/resources/css/header.css
  src/main/webapp/resources/css/page/account-transfer.css
  src/main/webapp/resources/css/sidebar.css
  src/main/webapp/resources/css/styles.css
  src/main/webapp/resources/js/account-transfer.js
Labels: ♻️ Refactor

#21 행원 목록 UI구현
  src/main/java/com/kcc/banking/domain/employee/controller/EmployeeController.java
  src/main/webapp/WEB-INF/views/employee-list.jsp
  src/main/webapp/resources/css/commonTable.css
Labels: ✨ Feature

#22 계좌이체 UI 구현
  src/main/webapp/resources/css/page/account-transfer.css
Labels: ✨ Feature

#26 행원 상세 UI구현
  src/main/java/com/kcc/banking/domain/employee/controller/EmployeeController.java
  src/main/webapp/WEB-INF/views/employee-detail.jsp
  src/main/webapp/resources/css/styles.css
Labels: ✨ Feature

#28 계좌 검색 모달 UI 구현
  src/main/webapp/WEB-INF/views/transfer/account-transfer.jsp
  src/main/webapp/resources/components/modal/account-search-modal.jsp
  src/main/webapp/resources/css/common-table.css
  src/main/webapp/resources/css/modal/account-search-modal.css
  src/main/webapp/resources/css/page/account-transfer.css
  src/main/webapp/resources/js/account-transfer.js
Labels: ✨ Feature

#29 행원 수정 UI 구현
  src/main/java/com/kcc/banking/domain/employee/controller/EmployeeController.java
  src/main/webapp/WEB-INF/views/auth/login-form.jsp
  src/main/webapp/WEB-INF/views/employee-update.jsp
  src/main/webapp/resources/components/modal/employee-search-modal.jsp
  src/main/webapp/resources/css/modal/employee-search-modal.css
  src/main/webapp/resources/css/styles.css
Labels: ✨ Feature

#31 Feature/#23 setting controller
  src/main/java/com/kcc/banking/domain/accountclose/controller/AccountCloseController.java
  src/main/java/com/kcc/banking/domain/accountclose/controller/AccountCloseRestController.java
  src/main/java/com/kcc/banking/domain/accountclose/dto/request/AccountStatus.java
  src/main/java/com/kcc/banking/domain/accountclose/mapper/AccountCloseMapper.java
  src/main/java/com/kcc/banking/domain/accountclose/service/AccountCloseService.java
  src/main/java/com/kcc/banking/domain/employee/controller/EmployeeController.java
  src/main/java/com/kcc/banking/domain/employee/controller/EmployeeRestController.java
  src/main/resources/mapper/accountCloseMapper.xml
  src/main/webapp/WEB-INF/views/account-close-cancel.jsp
  src/main/webapp/WEB-INF/views/account-close.jsp
Labels: ✨ Feature

#33 trade 테이블 해지 거래 내역 생성 api 완료
  src/main/java/com/kcc/banking/domain/accountclose/controller/AccountCloseRestController.java
  src/main/java/com/kcc/banking/domain/accountclose/dto/request/AccountStatus.java
  src/main/java/com/kcc/banking/domain/accountclose/dto/request/CloseTrade.java
  src/main/java/com/kcc/banking/domain/accountclose/mapper/AccountCloseMapper.java
  src/main/java/com/kcc/banking/domain/accountclose/service/AccountCloseService.java
  src/main/java/com/kcc/banking/domain/employee/controller/EmployeeController.java
  src/main/resources/mapper/accountCloseMapper.xml
Labels: ✨ Feature

#35 계좌 전체 조회 api
  src/main/java/com/kcc/banking/domain/account/controller/AccountRestController.java
  src/main/java/com/kcc/banking/domain/account/dto/response/AccountDetail.java
  src/main/java/com/kcc/banking/domain/account/mapper/AccountMapper.java
  src/main/java/com/kcc/banking/domain/account/service/AccountService.java
  src/main/java/com/kcc/banking/domain/employee/controller/EmployeeController.java
  src/main/resources/mapper/accountMapper.xml
  src/main/webapp/WEB-INF/views/transfer/account-transfer.jsp
  src/main/webapp/resources/components/modal/account-search-modal.jsp
  src/main/webapp/resources/js/modal/account-search-modal.js
  src/main/webapp/resources/js/page/account-transfer.js
Labels: ✨ Feature

#39 영업일 관리 UI 구현
  src/main/java/com/kcc/banking/domain/businessday/controller/BusinessDayController.java
  src/main/webapp/WEB-INF/views/businessday-management.jsp
  src/main/webapp/WEB-INF/views/employee-detail.jsp
  src/main/webapp/WEB-INF/views/employee-list.jsp
  src/main/webapp/WEB-INF/views/employee-save.jsp
  src/main/webapp/resources/components/modal/businessday-update-modal.jsp
  src/main/webapp/resources/css/modal/businessday-update-modal.css
Labels: ✨ Feature

#40 계좌 검색 모달 기능 구현
  src/main/java/com/kcc/banking/domain/account/controller/AccountRestController.java
  src/main/java/com/kcc/banking/domain/account/dto/request/SearchAccountOfModal.java
  src/main/java/com/kcc/banking/domain/account/dto/response/AccountOfModal.java
  src/main/java/com/kcc/banking/domain/account/mapper/AccountMapper.java
  src/main/java/com/kcc/banking/domain/account/service/AccountService.java
  src/main/java/com/kcc/banking/domain/account_transfer/controller/TransferController.java
  src/main/java/com/kcc/banking/domain/account_transfer/controller/TransferRestController.java
  src/main/resources/mapper/accountMapper.xml
  src/main/webapp/resources/assets/checkbox-active.png
  src/main/webapp/resources/assets/checkbox-unactive.png
  src/main/webapp/resources/css/modal/account-search-modal.css
  src/main/webapp/resources/js/modal/account-search-modal.js
Labels: ✨ Feature

#42 마감일 관리(행원) UI 구현
  src/main/java/com/kcc/banking/domain/employee/controller/EmployeeController.java
  src/main/webapp/WEB-INF/views/deadline-management.jsp
  src/main/webapp/resources/css/deadline-management.css
Labels: ✨ Feature

#44 마감일 관리(매니저) UI 구현
  src/main/java/com/kcc/banking/domain/employee/controller/EmployeeController.java
  src/main/webapp/WEB-INF/views/deadline-management2.jsp
  src/main/webapp/resources/css/common-table.css
Labels: ✨ Feature

#45 Feature/#34 cancellation account inquiry
  src/main/java/com/kcc/banking/domain/account_close/controller/AccountCloseController.java
  src/main/java/com/kcc/banking/domain/account_close/controller/AccountCloseRestController.java
  src/main/java/com/kcc/banking/domain/account_close/dto/request/AccountStatus.java
  src/main/java/com/kcc/banking/domain/account_close/dto/request/CloseTrade.java
  src/main/java/com/kcc/banking/domain/account_close/dto/response/CloseAccount.java
  src/main/java/com/kcc/banking/domain/account_close/dto/response/CloseAccountTotal.java
  src/main/java/com/kcc/banking/domain/account_close/dto/response/InterestSum.java
  src/main/java/com/kcc/banking/domain/account_close/mapper/AccountCloseMapper.java
  src/main/java/com/kcc/banking/domain/account_close/service/AccountCloseService.java
  src/main/java/com/kcc/banking/domain/accountclose/mapper/AccountCloseMapper.java
  src/main/java/com/kcc/banking/domain/accountclose/service/AccountCloseService.java
  src/main/resources/mapper/accountCloseMapper.xml
  src/main/webapp/WEB-INF/views/account_close/account-close-cancel.jsp
  src/main/webapp/WEB-INF/views/account_close/account-close.jsp
Labels: ✨ Feature

#49 AccountMapper LIKE 추가
  src/main/resources/mapper/accountMapper.xml
  src/main/webapp/WEB-INF/views/transfer/account-transfer.jsp
  src/main/webapp/resources/components/modal/account-search-modal.jsp
  src/main/webapp/resources/css/modal/account-search-modal.css
  src/main/webapp/resources/css/page/account-transfer.css
  src/main/webapp/resources/js/modal/account-search-modal.js
Labels: ✨ Feature

#50 기본 버튼 호버 추가 & API 파라미터 수정
  src/main/java/com/kcc/banking/domain/account/dto/request/SearchAccountOfModal.java
  src/main/java/com/kcc/banking/domain/account/dto/response/AccountOfModal.java
  src/main/resources/mapper/accountMapper.xml
  src/main/webapp/WEB-INF/views/transfer/account-transfer.jsp
  src/main/webapp/resources/components/modal/account-search-modal.jsp
  src/main/webapp/resources/css/modal/account-search-modal.css
  src/main/webapp/resources/css/page/account-transfer.css
  src/main/webapp/resources/css/styles.css
  src/main/webapp/resources/js/modal/account-search-modal.js
Labels: ✨ Feature

#51 Feature/#46 account close UI
  src/main/java/com/kcc/banking/domain/account_close/controller/AccountCloseRestController.java
  src/main/java/com/kcc/banking/domain/account_close/dto/request/StatusWithTrade.java
  src/main/java/com/kcc/banking/domain/account_close/service/AccountCloseService.java
  src/main/webapp/WEB-INF/views/account_close/account-close.jsp
  src/main/webapp/resources/css/page/account-close.css
Labels: ✨ Feature

#52 행원 추가 기능 구현
  src/main/java/com/kcc/banking/domain/employee/controller/EmployeeController.java
  src/main/java/com/kcc/banking/domain/employee/controller/EmployeeRestController.java
  src/main/java/com/kcc/banking/domain/employee/dto/request/EmployeeCreate.java
  src/main/java/com/kcc/banking/domain/employee/dto/response/CreatedEmployee.java
  src/main/java/com/kcc/banking/domain/employee/mapper/EmployeeMapper.java
  src/main/java/com/kcc/banking/domain/employee/service/EmployeeService.java
  src/main/resources/mapper/employeeMapper.xml
  src/main/webapp/WEB-INF/views/employee-save.jsp
  src/main/webapp/resources/components/modal/employee-detail-modal.jsp
  src/main/webapp/resources/css/common-table.css
  src/main/webapp/resources/css/modal/employee-detail-modal.css
  src/main/webapp/resources/js/employee-save.js
Labels: ✨ Feature

#54 계좌이체 계좌 불러오기 및 동적 버튼 구현
  src/main/webapp/WEB-INF/views/transfer/account-transfer.jsp
  src/main/webapp/resources/components/modal/account-search-modal.jsp
  src/main/webapp/resources/css/modal/account-search-modal.css
  src/main/webapp/resources/css/page/account-transfer.css
  src/main/webapp/resources/js/modal/account-search-modal.js
  src/main/webapp/resources/js/page/account-transfer.js
Labels: ✨ Feature

#55 계좌개설 저장 api 구현
  src/main/java/com/kcc/banking/domain/account/controller/AccountRestController.java
  src/main/java/com/kcc/banking/domain/account/dto/request/AccountCreate.java
  src/main/java/com/kcc/banking/domain/account/dto/response/AccountProductInfo.java
  src/main/java/com/kcc/banking/domain/account/mapper/AccountMapper.java
  src/main/java/com/kcc/banking/domain/account/service/AccountService.java
  src/main/java/com/kcc/banking/domain/customer/controller/CustomerRestController.java
  src/main/resources/mapper/accountMapper.xml
  src/main/webapp/WEB-INF/views/account/account-open.jsp
  src/main/webapp/resources/components/modal/show-search-customer-modal.jsp
  src/main/webapp/resources/css/common-table.css
Labels: ✨ Feature

#58 단일 계좌 모달 선택 시 tet/val 설정 추가
  src/main/webapp/resources/js/modal/account-search-modal.js
Labels: ✨ Feature

#59 refactor: DB 변경 empId->registrantId
  src/main/java/com/kcc/banking/domain/account/dto/request/AccountCreate.java
  src/main/java/com/kcc/banking/domain/account/dto/response/AccountDetail.java
  src/main/java/com/kcc/banking/domain/account_close/dto/request/AccountStatus.java
  src/main/java/com/kcc/banking/domain/account_close/dto/request/CloseTrade.java
  src/main/java/com/kcc/banking/domain/account_close/service/AccountCloseService.java
  src/main/resources/mapper/accountCloseMapper.xml
  src/main/resources/mapper/accountMapper.xml
  src/main/webapp/resources/components/modal/employee-detail-modal.jsp
  src/main/webapp/resources/js/employee-save.js
  src/main/webapp/resources/js/modal/account-search-modal.js
  src/main/webapp/resources/js/page/account-transfer.js
Labels: ♻️ Refactor

#60 fix: setEmpId->setRegistrantId AND modifierId 1L
  src/main/java/com/kcc/banking/domain/account/service/AccountService.java
  src/main/java/com/kcc/banking/domain/account_close/service/AccountCloseService.java
Labels: 🐛 BugFix

#62 사원 목록 검색 기능 구현
  src/main/java/com/kcc/banking/domain/employee/controller/EmployeeController.java
  src/main/java/com/kcc/banking/domain/employee/controller/EmployeeRestController.java
  src/main/java/com/kcc/banking/domain/employee/dto/request/EmployeeSearch.java
  src/main/java/com/kcc/banking/domain/employee/dto/response/EmployeeDataOfList.java
  src/main/java/com/kcc/banking/domain/employee/dto/response/EmployeeDetail.java
  src/main/java/com/kcc/banking/domain/employee/mapper/EmployeeMapper.java
  src/main/java/com/kcc/banking/domain/employee/service/EmployeeService.java
  src/main/resources/mapper/employeeMapper.xml
  src/main/webapp/WEB-INF/views/employee-list.jsp
  src/main/webapp/resources/css/employee-list.css
  src/main/webapp/resources/js/employee-list.js
Labels: ✨ Feature

#64 버튼 수정
  src/main/webapp/WEB-INF/views/employee-update.jsp
  src/main/webapp/resources/css/styles.css
Labels: ♻️ Refactor

#65 검색 버튼 CSS 통일
  src/main/webapp/WEB-INF/views/account/account-open.jsp
  src/main/webapp/WEB-INF/views/employee-update.jsp
  src/main/webapp/resources/css/styles.css
Labels: ♻️ Refactor

#66 Feature/#46 account close UI js
  src/main/java/com/kcc/banking/domain/account_close/service/AccountCloseService.java
  src/main/webapp/WEB-INF/views/account_close/account-close.jsp
  src/main/webapp/resources/css/page/account-close.css
  src/main/webapp/resources/js/modal/account-search-modal.js
  src/main/webapp/resources/js/page/account-close.js
Labels: ✨ Feature

#67 계좌조회 모달 ID 변경
  src/main/webapp/WEB-INF/views/transfer/account-transfer.jsp
  src/main/webapp/resources/components/modal/account-search-modal.jsp
  src/main/webapp/resources/css/common-table.css
  src/main/webapp/resources/css/modal/account-search-modal.css
  src/main/webapp/resources/css/page/account-transfer.css
  src/main/webapp/resources/css/styles.css
  src/main/webapp/resources/js/modal/account-search-modal.js
  src/main/webapp/resources/js/page/account-transfer.js
Labels: ♻️ Refactor

#68 account close UI
  src/main/webapp/WEB-INF/views/account_close/account-close.jsp
  src/main/webapp/resources/js/page/account-close.js
Labels: ✨ Feature

#69 공통 UI main-area & common-table 변경 및 & 고객 search modal 구현
  src/main/java/com/kcc/banking/domain/account/controller/AccountRestController.java
  src/main/java/com/kcc/banking/domain/account/service/AccountService.java
  src/main/java/com/kcc/banking/domain/customer/controller/CustomerRestController.java
  src/main/java/com/kcc/banking/domain/customer/dto/response/CustomerSearchDTO.java
  src/main/resources/mapper/customerMapper.xml
  src/main/webapp/WEB-INF/views/account/account-open.jsp
  src/main/webapp/resources/components/modal/search-customer-modal.jsp
  src/main/webapp/resources/components/modal/show-search-customer-modal.jsp
  src/main/webapp/resources/js/modal/search-customer-modal.js
  src/main/webapp/resources/js/page/account-open.js
Labels: ♻️ Refactor

#73 accountcloseJs 마무리
  src/main/webapp/WEB-INF/views/account_close/account-close.jsp
  src/main/webapp/resources/css/page/account-close.css
  src/main/webapp/resources/js/page/account-close.js
Labels: ✨ Feature

#74 행원 CRUD 리팩토링
  src/main/java/com/kcc/banking/domain/employee/controller/EmployeeController.java
  src/main/webapp/WEB-INF/views/employee-detail.jsp
  src/main/webapp/WEB-INF/views/employee/employee-list.jsp
  src/main/webapp/WEB-INF/views/employee/employee-save.jsp
  src/main/webapp/WEB-INF/views/employee/employee-update.jsp
  src/main/webapp/resources/components/modal/employee-detail-modal.jsp
  src/main/webapp/resources/css/modal/employee-detail-modal.css
  src/main/webapp/resources/css/page/employee-list.css
  src/main/webapp/resources/js/employee-list.js
  src/main/webapp/resources/js/employee-save.js
  src/main/webapp/resources/js/employee-update.js
  src/main/webapp/resources/js/modal/employee-detail-modal.js
  src/main/webapp/resources/js/page/employee-list.js
  src/main/webapp/resources/js/page/employee-save.js
  src/main/webapp/resources/js/page/employee-update.js
Labels: ♻️ Refactor

#77 로그인 및 헤더 갱신 기능 구현
  pom.xml
  src/main/java/com/kcc/banking/common/auth/PrincipalDetail.java
  src/main/java/com/kcc/banking/common/auth/PrincipalDetailService.java
  src/main/java/com/kcc/banking/common/auth/SecurityConfig.java
  src/main/java/com/kcc/banking/domain/employee/controller/EmployeeController.java
  src/main/java/com/kcc/banking/domain/employee/controller/EmployeeRestController.java
  src/main/java/com/kcc/banking/domain/employee/dto/response/AuthData.java
  src/main/java/com/kcc/banking/domain/employee/mapper/EmployeeMapper.java
  src/main/java/com/kcc/banking/domain/employee/service/EmployeeService.java
  src/main/resources/mapper/employeeMapper.xml
  src/main/webapp/resources/components/header.jsp
  src/main/webapp/resources/css/header.css
  src/main/webapp/resources/css/sidebar.css
  src/main/webapp/resources/js/header.js
Labels: ✨ Feature

#79 현재 영업일 API구현 및 헤더 연결
  src/main/java/com/kcc/banking/common/util/AuthenticationUtils.java
  src/main/java/com/kcc/banking/domain/businessday/controller/BusinessDayRestController.java
  src/main/java/com/kcc/banking/domain/businessday/dto/CurrentBusinessDay.java
  src/main/java/com/kcc/banking/domain/businessday/mapper/BusinessDayMapper.java
  src/main/java/com/kcc/banking/domain/businessday/service/BusinessDayService.java
  src/main/java/com/kcc/banking/domain/employee/dto/response/AuthData.java
  src/main/java/com/kcc/banking/domain/employee/service/EmployeeService.java
  src/main/resources/mapper/businessDayMapper.xml
  src/main/webapp/resources/components/header.jsp
  src/main/webapp/resources/css/header.css
  src/main/webapp/resources/js/header.js
Labels: ✨ Feature

#82 헤더 여백 지정 및 사이드바 id수정
  src/main/webapp/WEB-INF/views/employee/employee-list.jsp
  src/main/webapp/resources/components/sidebar.jsp
  src/main/webapp/resources/css/header.css
  src/main/webapp/resources/css/sidebar.css
  src/main/webapp/resources/css/styles.css
Labels: ♻️ Refactor

#84 영업일 관리 기능 구현(1)
  src/main/java/com/kcc/banking/common/util/AuthenticationUtils.java
  src/main/java/com/kcc/banking/domain/businessday/controller/BusinessDayController.java
  src/main/java/com/kcc/banking/domain/businessday/controller/BusinessDayRestController.java
  src/main/java/com/kcc/banking/domain/businessday/dto/response/BusinessDay.java
  src/main/java/com/kcc/banking/domain/businessday/mapper/BusinessDayMapper.java
  src/main/java/com/kcc/banking/domain/businessday/service/BusinessDayService.java
  src/main/java/com/kcc/banking/domain/employee/controller/EmployeeController.java
  src/main/java/com/kcc/banking/domain/employee/controller/EmployeeRestController.java
  src/main/java/com/kcc/banking/domain/employee/dto/request/BusinessDateAndBranchId.java
  src/main/java/com/kcc/banking/domain/employee/dto/request/EmployeeSearch.java
  src/main/java/com/kcc/banking/domain/employee/dto/response/AuthData.java
  src/main/java/com/kcc/banking/domain/employee/dto/response/CashBalanceOfBranch.java
  src/main/java/com/kcc/banking/domain/employee/dto/response/CashBalanceOfEmployee.java
  src/main/java/com/kcc/banking/domain/employee/mapper/EmployeeMapper.java
  src/main/java/com/kcc/banking/domain/employee/service/EmployeeService.java
  src/main/resources/mapper/businessDayMapper.xml
  src/main/resources/mapper/employeeMapper.xml
  src/main/webapp/WEB-INF/views/business-day/business-day-management.jsp
  src/main/webapp/WEB-INF/views/business-day/deadline-management.jsp
  src/main/webapp/WEB-INF/views/business-day/deadline-management2.jsp
  src/main/webapp/resources/components/modal/business-day-update-modal.jsp
  src/main/webapp/resources/components/modal/businessday-update-modal.jsp
  src/main/webapp/resources/css/modal/businessday-update-modal.css
  src/main/webapp/resources/css/styles.css
  src/main/webapp/resources/js/header.js
  src/main/webapp/resources/js/modal/business-day-update-modal.js
  src/main/webapp/resources/js/page/business-day-management.js
Labels: ✨ Feature

#85 Feature/#75 account close cancel UI
  src/main/java/com/kcc/banking/domain/account_close/service/AccountCloseService.java
  src/main/webapp/WEB-INF/views/account_close/account-close-cancel.jsp
  src/main/webapp/WEB-INF/views/account_close/account-close.jsp
  src/main/webapp/resources/js/page/account-close.js
Labels: ✨ Feature

#87 계좌이체 기능 구현
  src/main/java/com/kcc/banking/common/auth/SecurityConfig.java
  src/main/java/com/kcc/banking/domain/account_transfer/controller/TransferController.java
  src/main/java/com/kcc/banking/domain/account_transfer/controller/TransferRestController.java
  src/main/java/com/kcc/banking/domain/account_transfer/dto/request/TransferCreate.java
  src/main/java/com/kcc/banking/domain/account_transfer/dto/response/TransferDetail.java
  src/main/java/com/kcc/banking/domain/account_transfer/mapper/TransferMapper.java
  src/main/java/com/kcc/banking/domain/account_transfer/service/TransferService.java
  src/main/resources/mapper/transferMapper.xml
  src/main/webapp/WEB-INF/views/transfer/account-transfer.jsp
  src/main/webapp/resources/components/modal/transfer-result-modal.jsp
  src/main/webapp/resources/css/page/account-transfer.css
  src/main/webapp/resources/js/page/account-transfer.js
Labels: ✨ Feature

#89 비밀번호 검증 기능 구현
  src/main/java/com/kcc/banking/domain/account/controller/AccountRestController.java
  src/main/java/com/kcc/banking/domain/account/dto/request/PasswordValidation.java
  src/main/java/com/kcc/banking/domain/account/mapper/AccountMapper.java
  src/main/java/com/kcc/banking/domain/account/service/AccountService.java
  src/main/resources/mapper/accountMapper.xml
Labels: ✨ Feature

#91 실행 시 기본 SQL문 자동 실행
  src/main/java/com/kcc/banking/common/init/InitData.java
  src/main/java/com/kcc/banking/domain/account_transfer/service/TransferService.java
  src/main/resources/data.sql
  src/main/resources/schema.sql
  src/main/webapp/WEB-INF/views/transfer/account-transfer.jsp
Labels: ✨ Feature

#92 거래번호 seq 추가
  src/main/java/com/kcc/banking/domain/account_transfer/service/TransferService.java
  src/main/resources/schema.sql
Labels: 🐛 BugFix

#93 fix: transferService
  src/main/java/com/kcc/banking/domain/account_transfer/service/TransferService.java
Labels: 🐛 BugFix

#95 더미 데이터 수정 / TransferDetail Builder 패턴 사용
  src/main/java/com/kcc/banking/domain/account_transfer/dto/response/TransferDetail.java
  src/main/java/com/kcc/banking/domain/account_transfer/mapper/TransferMapper.java
  src/main/java/com/kcc/banking/domain/account_transfer/service/TransferService.java
  src/main/resources/data.sql
  src/main/resources/mapper/transferMapper.xml
  src/main/resources/schema.sql
  src/main/webapp/resources/js/page/account-transfer.js
Labels: 🐛 BugFix, ✨ Feature

#96 fix: data.sql balance
  src/main/resources/data.sql
Labels: 🐛 BugFix

#97 fix: data.sql balance
  src/main/resources/data.sql
Labels: 🐛 BugFix

#98 fix: deposit balance
  src/main/java/com/kcc/banking/domain/account_transfer/service/TransferService.java
Labels: 🐛 BugFix

#99 이체결과 모달 UI 수정
  src/main/webapp/resources/components/modal/transfer-result-modal.jsp
Labels: ✨ Feature

#102 영업일 마감 관리 기능 구현
  src/main/java/com/kcc/banking/common/auth/SecurityConfig.java
  src/main/java/com/kcc/banking/domain/account_transfer/service/TransferService.java
  src/main/java/com/kcc/banking/domain/business_day/controller/BusinessDayController.java
  src/main/java/com/kcc/banking/domain/business_day/controller/BusinessDayRestController.java
  src/main/java/com/kcc/banking/domain/business_day/dto/response/BusinessDay.java
  src/main/java/com/kcc/banking/domain/business_day/mapper/BusinessDayMapper.java
  src/main/java/com/kcc/banking/domain/business_day/service/BusinessDayService.java
  src/main/java/com/kcc/banking/domain/business_day_close/controller/BusinessDayCloseController.java
  src/main/java/com/kcc/banking/domain/business_day_close/controller/BusinessDayCloseRestController.java
  src/main/java/com/kcc/banking/domain/business_day_close/dto/request/BusinessDateAndEmployeeId.java
  src/main/java/com/kcc/banking/domain/business_day_close/dto/response/ClosingData.java
  src/main/java/com/kcc/banking/domain/business_day_close/dto/response/EmployeeClosingData.java
  src/main/java/com/kcc/banking/domain/business_day_close/dto/response/ManagerClosingData.java
  src/main/java/com/kcc/banking/domain/business_day_close/mapper/BusinessDayCloseMapper.java
  src/main/java/com/kcc/banking/domain/business_day_close/service/BusinessDayCloseService.java
  src/main/java/com/kcc/banking/domain/employee/service/EmployeeService.java
  src/main/java/com/kcc/banking/domain/trade/dto/response/TradeByCash.java
  src/main/java/com/kcc/banking/domain/trade/mapper/TradeMapper.java
  src/main/java/com/kcc/banking/domain/trade/service/TradeService.java
  src/main/resources/mapper/businessDayCloseMapper.xml
  src/main/resources/mapper/businessDayMapper.xml
  src/main/resources/mapper/tradeMapper.xml
  src/main/webapp/WEB-INF/views/business-day/deadline-management.jsp
  src/main/webapp/WEB-INF/views/business-day/deadline-management2.jsp
  src/main/webapp/WEB-INF/views/business-day/employee-close.jsp
  src/main/webapp/WEB-INF/views/business-day/manager-close.jsp
  src/main/webapp/resources/components/header.jsp
  src/main/webapp/resources/css/deadline-management.css
  src/main/webapp/resources/css/header.css
  src/main/webapp/resources/css/styles.css
  src/main/webapp/resources/js/page/employee-close.js
  src/main/webapp/resources/js/page/manager-close.js
Labels: ✨ Feature
